import { type KinoheldCinemasType } from "@waslaeuftin/helpers/kinoheld/helpers/kinoHeldCinemaSlugs";

export const CorrectedCinemas: Record<KinoheldCinemasType, string> = {
  cinemotion_berlin_hohenschoenhausen: "cinemotion-berlin-hohenschoenhausen",
  traumpalast_leonberg: "traumpalast-leonberg",
  traumpalast_schorndorf: "traumpalast-schorndorf",
  "corona.kinoplex.kaufbeuren": "corona.kinoplex.kaufbeuren",
  das_lumen_filmtheater_dueren: "das-lumen-filmtheater-dueren",
  xinedome_ulm: "xinedome-ulm",
  traumpalast_esslingen: "traumpalast-esslingen",
  das_lumen_filmtheater_solingen: "das-lumen-filmtheater-solingen",
  kinodrom_bocholt: "kinodrom-bocholt",
  traumpalast_waiblingen: "traumpalast-waiblingen",
  traumpalast_schwaebisch_gmuend: "traumpalast-schwaebisch-gmuend",
  filmwelt_landau: "filmwelt-landau",
  staufen_movieplex_goeppingen: "staufen-movieplex-goeppingen",
  seven_kinocenter_gummersbach: "seven-kinocenter-gummersbach",
  colosseum_center: "colosseum-center",
  tichelpark_cinemas_kleve: "tichelpark-cinemas-kleve",
  comet_cine_center_moenchengladbach: "comet-cine-center-moenchengladbach",
  traumpalast_nuertingen: "traumpalast-nuertingen",
  kinorama_unna_new: "kinorama-unna-new",
  capitol_filmpalast_albstadt: "capitol-filmpalast-albstadt",
  filmwelt_schweinfurt: "filmwelt-schweinfurt",
  capitol_kino_plauen: "capitol-kino-plauen",
  cinemoon_pforzheim: "cinemoon-pforzheim",
  cinemotion_bremerhaven: "cinemotion-bremerhaven",
  cinewood_kinocenter_waldkraiburg: "cinewood-kinocenter-waldkraiburg",
  regina_palast: "regina-palast",
  cineworld_luenen: "cineworld-luenen",
  cinema_ahaus: "cinema-ahaus",
  cinecity_und_kammer_filmtheater_crailsheim:
    "cinecity-und-kammer-filmtheater-crailsheim",
  movietown_wust: "movietown-wust",
  filmzentrum_baeren_boeblingen: "filmzentrum-baeren-boeblingen",
  cinema_duelmen: "cinema-duelmen",
  kinocenter_theaterhaus_speyer: "kinocenter-theaterhaus-speyer",
  kino_meppen: "kino-meppen",
  cinema_coesfeld: "cinema-coesfeld",
  kino_aurich: "kino-aurich",
  lichtburg_filmpalast_oberhausen: "lichtburg-filmpalast-oberhausen",
  royal_filmpalast: "royal-filmpalast",
  filmpalast_capitol: "filmpalast-capitol",
  uc_kino_ruegencenter_bergen_auf_ruegen:
    "uc-kino-ruegencenter-bergen-auf-ruegen",
  filmpalast_maxx_hameln: "filmpalast-maxx-hameln",
  kinocenter_borken: "kinocenter-borken",
  kino_papenburg: "kino-papenburg",
  movie_magic_eberswalde: "movie-magic-eberswalde",
  passage_kinos_leipzig: "passage-kinos-leipzig",
  central_kino_hof: "central-kino-hof",
  starmexx_erlebniskino_burglengenfeld: "starmexx-erlebniskino-burglengenfeld",
  isar_kinocenter_bad_toelz: "isar-kinocenter-bad-toelz",
  wandelhof_extra_kinowelt_schwarzheide:
    "wandelhof-extra-kinowelt-schwarzheide",
  lichtspielhaus_deggendorf: "lichtspielhaus-deggendorf",
  cinemotion_hoyerswerda: "cinemotion-hoyerswerda",
  traumpalast_backnang: "traumpalast-backnang",
  filmpalast_am_hafen_nienburg: "filmpalast-am-hafen-nienburg",
  cinema_dachau: "cinema-dachau",
  capitol: "capitol",
  cinemotion_luedinghausen: "cinemotion-luedinghausen",
  concerthaus_kino_brandenburg: "concerthaus-kino-brandenburg",
  capitol_movieworld_saarlouis: "capitol-movieworld-saarlouis",
  cine_5_asbach: "cine-5-asbach",
  kino_center_leer: "kino-center-leer",
  em_kino_stuttgart: "em-kino-stuttgart",
  cid_cinema_in_doebeln: "cid-cinema-in-doebeln",
  hackesche_hoefe_kino: "hackesche-hoefe-kino",
  filmpalast_oranienburg: "filmpalast-oranienburg",
  cinexx_hachenburg: "cinexx-hachenburg",
  kinocenter_trifthof_weilheim: "kinocenter-trifthof-weilheim",
  thalia_das_programmkino_potsdam: "thalia-das-programmkino-potsdam",
  grefi_kino_grevenbroich: "grefi-kino-grevenbroich",
  cinemotion_langenhagen: "cinemotion-langenhagen",
  cineplanet_5_bad_segeberg: "cineplanet-5-bad-segeberg",
  haveltorkino: "haveltorkino",
  programmkino_ost_dresden: "programmkino-ost-dresden",
  burgtheater: "burgtheater",
  broadway_trier: "broadway-trier",
  "movie_star_kino_dillenburg ": "movie-star-kino-dillenburg ",
  apollo_kino_ibbenbüren: "apollo-kino-ibbenbüren",
  ut_kinos_saarbruecken: "ut-kinos-saarbruecken",
  cinecenter_cloppenburg: "cinecenter-cloppenburg",
  movie_star_kino_guestrow: "movie-star-kino-guestrow",
  herzogtheater_geldern: "herzogtheater-geldern",
  thalia_kino_berlin: "thalia-kino-berlin",
  bruehl_cinema_zeitz: "bruehl-cinema-zeitz",
  casino_lichtspiele_meiningen: "casino-lichtspiele-meiningen",
  cinenova_kino_koeln: "cinenova-kino-koeln",
  lichtburg: "lichtburg",
  movie_star_bad_schwartau: "movie-star-bad-schwartau",
  linden_lichtspiele_ilmenau: "linden-lichtspiele-ilmenau",
  union_filmtheater_neuruppin: "union-filmtheater-neuruppin",
  cinema_europa: "cinema-europa",
  kino_biigz: "kino-biigz",
  uppstall_kinos_stendal: "uppstall-kinos-stendal",
  movies_bad_mergentheim: "movies-bad-mergentheim",
  babylon_berlin: "babylon-berlin",
  abaton_kino_hamburg: "abaton-kino-hamburg",
  woki: "woki",
  kino_center: "kino-center",
  gloria_stuttgart: "gloria-stuttgart",
  kempener_lichtspiele: "kempener-lichtspiele",
  filmpalast_aschersleben: "filmpalast-aschersleben",
  movie_star_kino_wittenberge: "movie-star-kino-wittenberge",
  passage_kino_hamburg: "passage-kino-hamburg",
  museum_lichtspiele_muenchen: "museum-lichtspiele-muenchen",
  capitol_filmpalast_schleswig: "capitol-filmpalast-schleswig",
  quadroscope_stadtkino_Burghausen: "quadroscope-stadtkino-Burghausen",
  kino_center_garmisch_aspen_im_lamm: "kino-center-garmisch-aspen-im-lamm",
  union_filmtheater_prenzlau: "union-filmtheater-prenzlau",
  filmtheater_weltspiegel: "filmtheater-weltspiegel",
  delphin_palast_wolfsburg: "delphin-palast-wolfsburg",
  oberland_kinocenter_hausham: "oberland-kinocenter-hausham",
  ut_99: "ut-99",
  capitol_3d_kino_herford: "capitol-3d-kino-herford",
  spectrum_kino_center_norderstedt: "spectrum-kino-center-norderstedt",
  gloria_kino_center_geislingen: "gloria-kino-center-geislingen",
  universum_kino: "universum-kino",
  movie_im_luitpoldhaus_marktheidenfeld:
    "movie-im-luitpoldhaus-marktheidenfeld",
  filmtheater_schauburg_dresden: "filmtheater-schauburg-dresden",
  apollo_kino_bar: "apollo-kino-bar",
  studio_filmtheater_am_dreiecksplatz: "studio-filmtheater-am-dreiecksplatz",
  gloria_filmpalast_annaberg_buchholz: "gloria-filmpalast-annaberg-buchholz",
  filmpalast_bernau: "filmpalast-bernau",
  schwanen_kinos_hechingen: "schwanen-kinos-hechingen",
  ring_kino_schwarzenberg: "ring-kino-schwarzenberg",
  cinema_frankfurt: "cinema-frankfurt",
  universum_kino_palast_bad_kissingen: "universum-kino-palast-bad-kissingen",
  central_lichtspiele_kinowelt_herzberg:
    "central-lichtspiele-kinowelt-herzberg",
  atelier_am_bollwerk_stuttgart: "atelier-am-bollwerk-stuttgart",
  neue_welt_kinocenter_weiden: "neue-welt-kinocenter-weiden",
  kino_rekord_lichtspiele_auerbach: "kino-rekord-lichtspiele-auerbach",
  metropol_center_neuwied: "metropol-center-neuwied",
  kinostar_arthaus_kino_heilbronn: "kinostar-arthaus-kino-heilbronn",
  kinostar_filmwelt_bretten: "kinostar-filmwelt-bretten",
  kinocenter_winsen: "kinocenter-winsen",
  eden_cinehouse: "eden-cinehouse",
  kinowelt: "kinowelt",
  cinema_wuppertal: "cinema-wuppertal",
  movie_star_kino_sangerhausen: "movie-star-kino-sangerhausen",
  cinemotion_itzehoe: "cinemotion-itzehoe",
  schloss_theater_miltenberg: "schloss-theater-miltenberg",
  rex_filmtheater_wuppertal: "rex-filmtheater-wuppertal",
  kino_union_friedrichshagen_berlin: "kino-union-friedrichshagen-berlin",
  b_ware_ladenkino: "b-ware-ladenkino",
  filmbuehne_mittweida: "filmbuehne-mittweida",
  kino_castello: "kino-castello",
  kinocenter_vor_dem_kremper_tor: "kinocenter-vor-dem-kremper-tor",
  kinostar_filmwelt_mosbach: "kinostar-filmwelt-mosbach",
  weltspiegel_kino: "weltspiegel-kino",
  lichtspiel_center: "lichtspiel-center",
  filmpalast_wolfenbuettel: "filmpalast-wolfenbuettel",
  gloria_filmpalast_erkelenz: "gloria-filmpalast-erkelenz",
  movies_kino_hofheim: "movies-kino-hofheim",
  leopold_kinos_muenchen: "leopold-kinos-muenchen",
  cinetower: "cinetower",
  kinocenter_rendsburg: "kinocenter-rendsburg",
  scala_programmkino_lueneburg: "scala-programmkino-lueneburg",
  kinocenter_weissenburg: "kinocenter-weissenburg",
  filmhaus_huber: "filmhaus-huber",
  burgtheater_kinos_hechingen: "burgtheater-kinos-hechingen",
  filmtheater_zwiesel: "filmtheater-zwiesel",
  casino_filmtheater_aschaffenburg: "casino-filmtheater-aschaffenburg",
  central_programmkino: "central-programmkino",
  kinocenter_rio_scala_hali: "kinocenter-rio-scala-hali",
  kinocenter: "kinocenter",
  rio_filmpalast_muenchen: "rio-filmpalast-muenchen",
  capitoltheater_bad_toelz: "capitoltheater-bad-toelz",
  astra_theater: "astra-theater",
  atlantis_kino_mannheim: "atlantis-kino-mannheim",
  monopol_kino: "monopol-kino",
  roxy_filmtheater_heinsberg: "roxy-filmtheater-heinsberg",
  schauburg_kino_bremen: "schauburg-kino-bremen",
  capitol_kino: "capitol-kino",
  toni_berlin: "toni-berlin",
  moviemento_kino: "moviemento-kino",
  odeon_lichtspieltheater_koeln: "odeon-lichtspieltheater-koeln",
  odeon_kino: "odeon-kino",
  delphi_filmtheater_weilburg: "delphi-filmtheater-weilburg",
  passage_kinos_saarbruecken: "passage-kinos-saarbruecken",
  kammer_lichtspiele_sonneberg: "kammer-lichtspiele-sonneberg",
  filmpalast_sulingen: "filmpalast-sulingen",
  apollo_filmtheater_limbach_oberfrohna:
    "apollo-filmtheater-limbach-oberfrohna",
  kino_central_freudenstadt: "kino-central-freudenstadt",
  scala_kulturpalast_werder: "scala-kulturpalast-werder",
  kinoparadies_oberndorf: "kinoparadies-oberndorf",
  universum_filmtheater_braunschweig: "universum-filmtheater-braunschweig",
  harmonie_theater_frankfurt: "harmonie-theater-frankfurt",
  delphi_arthaus_kino_stuttgart: "delphi-arthaus-kino-stuttgart",
  lichthaus_kino_im_strassenbahndepot_weimar:
    "lichthaus-kino-im-strassenbahndepot-weimar",
  liliom_augsburg: "liliom-augsburg",
  thalia_lichtspiele_bous: "thalia-lichtspiele-bous",
  volkslichtspiele: "volkslichtspiele",
  koralle_lichtspielhaus: "koralle-lichtspielhaus",
  linden_theater_meschede: "linden-theater-meschede",
  corso_kino_mayen: "corso-kino-mayen",
  metropol: "metropol",
  gloria_gloriette: "gloria-gloriette",
  lichtspielhaus_fuerstenfeldbruck: "lichtspielhaus-fuerstenfeldbruck",
  neue_kammerspiele_kleinmachnow: "neue-kammerspiele-kleinmachnow",
  kamera_filmkunsttheater: "kamera-filmkunsttheater",
  corso_filmpalast_hueckelhoven: "corso-filmpalast-hueckelhoven",
  traumpalast_imax_leonberg: "traumpalast-imax-leonberg",
  kino_haar: "kino-haar",
  weisshaus_kino_koeln: "weisshaus-kino-koeln",
  casablanca_filmkunsttheater_nuernberg:
    "casablanca-filmkunsttheater-nuernberg",
  schmelzer_lichtspiele: "schmelzer-lichtspiele",
  movie_star_kino_perleberg: "movie-star-kino-perleberg",
  kino_astoria_wittstock: "kino-astoria-wittstock",
  lichtwerk: "lichtwerk",
  union_filmtheater_immenstadt: "union-filmtheater-immenstadt",
  kino_roxy_lichtspiele: "kino-roxy-lichtspiele",
  buender_lichtspiele: "buender-lichtspiele",
  filmkunst_66_berlin: "filmkunst-66-berlin",
  scala_cinema: "scala-cinema",
  cinepark_krumbach: "cinepark-krumbach",
  bali_kinos: "bali-kinos",
  kino_ottobrunn: "kino-ottobrunn",
  rex_lichtspieltheater_bonn: "rex-lichtspieltheater-bonn",
  kino_bad_driburg: "kino-bad-driburg",
  kino_gelnhausen_pali_casino: "kino-gelnhausen-pali-casino",
  hansa_kino_lemgo: "hansa-kino-lemgo",
  loewenlichtspiele_rudersberg: "loewenlichtspiele-rudersberg",
  krone_lichtspiele_nagold: "krone-lichtspiele-nagold",
  parktheater_und_studio_lindau: "parktheater-und-studio-lindau",
  hansa_kino: "hansa-kino",
  saalbau_lichtspiele_rodgau: "saalbau-lichtspiele-rodgau",
  kino_lichtblick_filmtheater_oldenburg:
    "kino-lichtblick-filmtheater-oldenburg",
  amper_lichtspiele_wolnzach: "amper-lichtspiele-wolnzach",
  weltspiegel_kino_finsterwalde: "weltspiegel-kino-finsterwalde",
  eulenspiegel_essen: "eulenspiegel-essen",
  off_broadway_kino_koeln: "off-broadway-kino-koeln",
  studio_kino_hamburg: "studio-kino-hamburg",
  city_46_bremen: "city-46-bremen",
  neues_ringtheater: "neues-ringtheater",
  kino_boizenburg: "kino-boizenburg",
  central_theater_grimma: "central-theater-grimma",
  cadillac_casablanca_kinocenter_ingelheim:
    "cadillac-casablanca-kinocenter-ingelheim",
  blankeneser_kino_hamburg: "blankeneser-kino-hamburg",
  neues_theater_sankt_wendel: "neues-theater-sankt-wendel",
  kuk_kino_und_kneipe_schweinfurt: "kuk-kino-und-kneipe-schweinfurt",
  filmgalerie_am_frauenmarkt_grossenhain:
    "filmgalerie-am-frauenmarkt-grossenhain",
  movieland_erkner: "movieland-erkner",
  starlight_kino_bad_neustadt: "starlight-kino-bad-neustadt",
  city_filmstudio_lebach: "city-filmstudio-lebach",
  union_theater_illingen: "union-theater-illingen",
  bambi_und_camera_kino_bad_schwalbach: "bambi-und-camera-kino-bad-schwalbach",
  kino_intimes_berlin: "kino-intimes-berlin",
  city_kino_wedding_berlin_ab: "city-kino-wedding-berlin-ab",
  metropol_am_postplatz_boeblingen: "metropol-am-postplatz-boeblingen",
  sputnik_kino: "sputnik-kino",
  maxim_kino: "maxim-kino",
  metropolis_kino: "metropolis-kino",
  elbe_filmtheater_hamburg: "elbe-filmtheater-hamburg",
  tilsiter_lichtspiele_programmkino_berlin:
    "tilsiter-lichtspiele-programmkino-berlin",
  kulturzentrum_linse: "kulturzentrum-linse",
  capitol_kino_in_bad_berleburg: "capitol-kino-in-bad-berleburg",
  centraltheater_brake: "centraltheater-brake",
  central_kino: "central-kino",
  cinema_stuttgart: "cinema-stuttgart",
  club_kino_zinnowitz: "club-kino-zinnowitz",
  neue_filmbuehne_bonn: "neue-filmbuehne-bonn",
  arena_filmtheater: "arena-filmtheater",
  scala_filmtheater_oehringen: "scala-filmtheater-oehringen",
  filmbuehne_postkutsche_dortmund: "filmbuehne-postkutsche-dortmund",
  filmstudio_glueckauf_essen: "filmstudio-glueckauf-essen",
  gondel_filmtheater_bremen: "gondel-filmtheater-bremen",
  loft: "loft",
  gloria_kino: "gloria-kino",
  kinos_im_andreasstadel_regensburg: "kinos-im-andreasstadel-regensburg",
  imax_3d_laser_4k_sinsheim: "imax-3d-laser-4k-sinsheim",
  luchs_kino_am_zoo_halle: "luchs-kino-am-zoo-halle",
  garbo_kino_regensburg: "garbo-kino-regensburg",
  studio_isabella_muenchen: "studio-isabella-muenchen",
  kino_berchtesgaden_im_kongresshaus: "kino-berchtesgaden-im-kongresshaus",
  kino_im_schillerhof: "kino-im-schillerhof",
  metropol_lichtspieltheater_wundervoll_rostock:
    "metropol-lichtspieltheater-wundervoll-rostock",
  gloria_center: "gloria-center",
  kinostar_scala_neckarsulm: "kinostar-scala-neckarsulm",
  bali_kino: "bali-kino",
  ostentor_kino_regensburg: "ostentor-kino-regensburg",
  burg_lichtspiele_karlstadt: "burg-lichtspiele-karlstadt",
  kinop_penzberg: "kinop-penzberg",
  abc_kino_muenchen: "abc-kino-muenchen",
  kamera: "kamera",
  burgtheater_bad_langensalza: "burgtheater-bad-langensalza",
  donau_lichtspiele_offingen: "donau-lichtspiele-offingen",
  filmtheater_union_fürstenwalde: "filmtheater-union-fürstenwalde",
  odeon_kino_mannheim: "odeon-kino-mannheim",
  kino_casablanca_berlin: "kino-casablanca-berlin",
  kino_passage_erlenbach: "kino-passage-erlenbach",
  lichtspiel_kino: "lichtspiel-kino",
  merkur_filmcenter_gaggenau: "merkur-filmcenter-gaggenau",
  burg_theater: "burg-theater",
  neues_krone_kino_lindenberg_im_allgaeu:
    "neues-krone-kino-lindenberg-im-allgaeu",
  cinema_im_ostertor: "cinema-im-ostertor",
  camera_am_holzberg: "camera-am-holzberg",
  kino_im_kulturhaus_berlin: "kino-im-kulturhaus-berlin",
  kino_am_markt_jena: "kino-am-markt-jena",
  capitol_kino_zeil: "capitol-kino-zeil",
  kino_lumiere_goettingen: "kino-lumiere-goettingen",
  neue_schauburg_burgdorf: "neue-schauburg-burgdorf",
  kino_im_buergerhaus: "kino-im-buergerhaus",
  kommunales_kino: "kommunales-kino",
  filmhaus_huber_bad_woerishofen: "filmhaus-huber-bad-woerishofen",
  kurtheater: "kurtheater",
  hochland_kino_garmisch_partenkirchen: "hochland-kino-garmisch-partenkirchen",
  kino_zukunft_berlin: "kino-zukunft-berlin",
  burg_filmtheater_fehmarn: "burg-filmtheater-fehmarn",
  atlantis_filmtheater_bremen: "atlantis-filmtheater-bremen",
  programmkino_im_audi_forum_ingolstadt:
    "programmkino-im-audi-forum-ingolstadt",
  obenkino_im_glad_house_cottbus: "obenkino-im-glad-house-cottbus",
  kommunales_kino_in_der_pumpe_kiel: "kommunales-kino-in-der-pumpe-kiel",
  il_kino: "il-kino",
  kommunales_kino_esslingen: "kommunales-kino-esslingen",
  lichtspieltheater_wundervoll_frieda_23_rostock:
    "lichtspieltheater-wundervoll-frieda-23-rostock",
  astra_filmtheater_ploen: "astra-filmtheater-ploen",
  kuki_das_kultkino: "kuki-das-kultkino",
  holi_filmtheater_oehringen: "holi-filmtheater-oehringen",
  schanzenkino_73: "schanzenkino-73",
  filmladen_kassel: "filmladen-kassel",
  kino_digital_im_hohenstaufensaal_annweiler_am_trifels:
    "kino-digital-im-hohenstaufensaal-annweiler-am-trifels",
  schauburg_kino_neuwied: "schauburg-kino-neuwied",
  rio_filmtheater_muelheim: "rio-filmtheater-muelheim",
  autokino_greifensteine_bei_geyer_anamare:
    "autokino-greifensteine-bei-geyer-anamare",
  brazil_programmkino_schwaebisch_gmuend:
    "brazil-programmkino-schwaebisch-gmuend",
  kommunales_kino_tivoli_achern: "kommunales-kino-tivoli-achern",
  kammerlichtspiele: "kammerlichtspiele",
  cinema_quadrat_mannheim: "cinema-quadrat-mannheim",
  alte_brennerei_schwake_ennigerloh: "alte-brennerei-schwake-ennigerloh",
  sonnenlichtspiele_gaildorf: "sonnenlichtspiele-gaildorf",
  kommunales_kino_weiterstadt: "kommunales-kino-weiterstadt",
  donau_lichtspiele_doli_woerth_an_der_donau:
    "donau-lichtspiele-doli-woerth-an-der-donau",
  eulenspiegelkino_mölln: "eulenspiegelkino-mölln",
  foolskino: "foolskino",
  filmstudio: "filmstudio",
  pastori_das_historische_lichtspielgasthaus_weilmuenster:
    "pastori-das-historische-lichtspielgasthaus-weilmuenster",
  zebra_kino_konstanz: "zebra-kino-konstanz",
  wied_scala: "wied-scala",
  filmbuehne_bad_nauheim: "filmbuehne-bad-nauheim",
  drehwerk_17_19_kino_wachtberg: "drehwerk-17-19-kino-wachtberg",
  filmrauschpalast: "filmrauschpalast",
  galerie_cinema: "galerie-cinema",
  filmraum_hamburg: "filmraum-hamburg",
  lichtblick_kino_berlin: "lichtblick-kino-berlin",
  die_filminsel_kommunales_kino_biblis: "die-filminsel-kommunales-kino-biblis",
  moviac_kino_im_kaiserhof: "moviac-kino-im-kaiserhof",
  berli_theater: "berli-theater",
  kino_deutsches_haus_meldorf: "kino-deutsches-haus-meldorf",
  filmtheater_wertingen: "filmtheater-wertingen",
  drehwerk_17_19_buehne_wachtberg: "drehwerk-17-19-buehne-wachtberg",
  traum_kino_kiel: "traum-kino-kiel",
  sommernachtskino_tuebingen: "sommernachtskino-tuebingen",
  forum_velbert: "forum-velbert",
  union_filmtheater_freiluftkino_berlin:
    "union-filmtheater-freiluftkino-berlin",
  capitol_theater_kino_kerpen: "capitol-theater-kino-kerpen",
  kabarett_limbach_oberfrohna: "kabarett-limbach-oberfrohna",
  cineo_dein_kino_in_der_wassermuehle_friesoythe:
    "cineo-dein-kino-in-der-wassermuehle-friesoythe",
  kino_auf_der_burg_esslingen: "kino-auf-der-burg-esslingen",
  kino_am_olympiasee: "kino-am-olympiasee",
  filmpalast: "filmpalast",
  norddeutsches_freiluftkino: "norddeutsches-freiluftkino",
  fuerstenfelder_kinosommer: "fuerstenfelder-kinosommer",
  open_air_kino_pforzheim: "open-air-kino-pforzheim",
  freiluftkino_hasenheide: "freiluftkino-hasenheide",
  em_festival_stuttgart: "em-festival-stuttgart",
  openair_kiel: "openair-kiel",
  swk_open_air_kino: "swk-open-air-kino",
  calwer_sommerkino_kloster_hirsau: "calwer-sommerkino-kloster-hirsau",
  kinosommer_am_waschhaus_potsdam: "kinosommer-am-waschhaus-potsdam",
  kino_union_am_kaisersteg: "kino-union-am-kaisersteg",
  scala_kino_center_hof: "scala-kino-center-hof",
  kurtheater_bad_homburg: "kurtheater-bad-homburg",
  mondscheinkino_am_hermannsdenkmal: "mondscheinkino-am-hermannsdenkmal",
  "mercedes_benz.com": "mercedes-benz.com",
  kino_openair_im_turm_baur: "kino-openair-im-turm-baur",
  openair_kino_im_schlosshof_ettlingen: "openair-kino-im-schlosshof-ettlingen",
  open_air_kino_kassel: "open-air-kino-kassel",
  freiluftkino_groemitz: "freiluftkino-groemitz",
  freiluftkino_insel_revier_suedost: "freiluftkino-insel-revier-suedost",
  campus_filmnächte_aschaffenburg: "campus-filmnächte-aschaffenburg",
  open_air_meppen: "open-air-meppen",
  open_air_papenburg: "open-air-papenburg",
  rio_palast: "rio-palast",
  b_ware_openair_fmp: "b-ware-openair-fmp",
  open_Air_Kino_Schloss_Schöningen: "open-Air-Kino-Schloss-Schöningen",
  open_air_kino_reutlingen: "open-air-kino-reutlingen",
  "open_air.schloß_schöningen": "open-air.schloß-schöningen",
  gemeinschaftshaus_langwasser_nuernberg:
    "gemeinschaftshaus-langwasser-nuernberg",
  open_air_kino_im_wildpark_bad_mergentheim:
    "open-air-kino-im-wildpark-bad-mergentheim",
  open_air_leutkirch: "open-air-leutkirch",
  "bonn.live.open.air.kino": "bonn.live.open.air.kino",
  apollo_theater_norden: "apollo-theater-norden",
  wittgensteiner_open_air_kino: "wittgensteiner-open-air-kino",
  sommernachts_kino_oberndorf: "sommernachts-kino-oberndorf",
  thf_cinema_berlin: "thf-cinema-berlin",
  openair_in_beelitz_heilstätten: "openair-in-beelitz-heilstätten",
  schauburg_open_air_stolberg: "schauburg-open-air-stolberg",
  hollywood_meets_hafenpark: "hollywood-meets-hafenpark",
  kino_im_park_in_gemmingen: "kino-im-park-in-gemmingen",
  erlebnis_autokino_minden: "erlebnis-autokino-minden",
  movie_nights_im_nells_park_hotel_trier:
    "movie-nights-im-nells-park-hotel-trier",
  nomadenkino_berlin: "nomadenkino-berlin",
  lichthaus_open_air_kino_weimar: "lichthaus-open-air-kino-weimar",
  autokino_st_ingbert: "autokino-st-ingbert",
  autokultur_kino_goettingen: "autokultur-kino-goettingen",
  kino_im_schlossgarten_altensteig: "kino-im-schlossgarten-altensteig",
  open_air_kino_travemünde: "open-air-kino-travemünde",
  open_air_kino_spandau: "open-air-kino-spandau",
  autokino_karpfham: "autokino-karpfham",
  central_kino_und_kultur_treuchtlingen:
    "central-kino-und-kultur-treuchtlingen",
  filmnaechte_in_burglengenfeld: "filmnaechte-in-burglengenfeld",
  gloria_service_kino_schmelz: "gloria-service-kino-schmelz",
  autokino_kemnath: "autokino-kemnath",
  autokino_schmitten: "autokino-schmitten",
  central_open_air_wuerzburg: "central-open-air-wuerzburg",
  kino_arsenal_tuebingen: "kino-arsenal-tuebingen",
  autokino_freilichtspiele_helmbrechts: "autokino-freilichtspiele-helmbrechts",
  achava_sommerkino_auf_der_seebühne_weimar:
    "achava-sommerkino-auf-der-seebühne-weimar",
  kino_atelier_und_cafe_haag_tuebingen: "kino-atelier-und-cafe-haag-tuebingen",
  tyroler_kino_kirchheim_unter_teck: "tyroler-kino-kirchheim-unter-teck",
  central_kino_open_air: "central-kino-open-air",
  "open.air.kino.freibad.hemkenrode": "open.air.kino.freibad.hemkenrode",
  b_ware_openair_prinzessinnengarten: "b-ware-openair-prinzessinnengarten",
  eldorado_arthouse_kino: "eldorado-arthouse-kino",
  kino_alte_brauerei_stegen: "kino-alte-brauerei-stegen",
  zentralkino_dresden: "zentralkino-dresden",
  kinoklub: "kinoklub",
  kino_krokodil: "kino-krokodil",
  walhalla_kinocenter: "walhalla-kinocenter",
  open_air_kino_im_blankenhorn_schliengen:
    "open-air-kino-im-blankenhorn-schliengen",
  rhoenlichtspiele: "rhoenlichtspiele",
  siegener_open_air_kino: "siegener-open-air-kino",
  burgfilmfest_wertheim: "burgfilmfest-wertheim",
  freiluftkino_moierhof_buxheim: "freiluftkino-moierhof-buxheim",
  autokino_georgsmarienhuette: "autokino-georgsmarienhuette",
  film_huber: "film-huber",
  lichtspielhaus_sohler_wangen: "lichtspielhaus-sohler-wangen",
  wolf_kino: "wolf-kino",
  kamino_reutlingen: "kamino-reutlingen",
  klick_kino_berlin: "klick-kino-berlin",
  kiwi_kino_bad_wildbad: "kiwi-kino-bad-wildbad",
  mobiles_kino_pforzheim: "mobiles-kino-pforzheim",
  open_air_im_schlosshof_sonnenlichtspiele_gaildorf:
    "open-air-im-schlosshof-sonnenlichtspiele-gaildorf",
  hall_of_fame: "hall-of-fame",
  lichtspiele_koeln_kalk: "lichtspiele-koeln-kalk",
  autokino_usedom: "autokino-usedom",
  zebra_kino_open_air: "zebra-kino-open-air",
  b_ware_openairprinzessinnengarten_kollektiv_neukoelln:
    "b-ware-openairprinzessinnengarten-kollektiv-neukoelln",
  mobiles_kino_bad_wildbad: "mobiles-kino-bad-wildbad",
  hall_of_fame_osnabrueck: "hall-of-fame-osnabrueck",
  open_air_kino_waldthurn: "open-air-kino-waldthurn",
  festzelt_waldstrand_fulda: "festzelt-waldstrand-fulda",
  open_air_kino_burhave: "open-air-kino-burhave",
  open_air_kino_hof: "open-air-kino-hof",
  sommerkino_im_tierpark_dessau: "sommerkino-im-tierpark-dessau",
  kulturhof_kroenbacken_erfurt: "kulturhof-kroenbacken-erfurt",
  open_air_kino_soltau: "open-air-kino-soltau",
  open_air_kino_im_rathauspark_hilter: "open-air-kino-im-rathauspark-hilter",
  kinoklub_im_schauspielhaus_erfurt: "kinoklub-im-schauspielhaus-erfurt",
  woerlitzer_filmtage: "woerlitzer-filmtage",
  open_air_kino_gammertingen: "open-air-kino-gammertingen",
  kronen_lichtspiele_rodgau: "kronen-lichtspiele-rodgau",
  sinema_transtopia_berlin: "sinema-transtopia-berlin",
  kino_melies_goettingen: "kino-melies-goettingen",
  gersthofer_kinosommer: "gersthofer-kinosommer",
  arena_sommerkino_wernigerode: "arena-sommerkino-wernigerode",
  mobile_kino_berlin: "mobile-kino-berlin",
  kino_im_bad_bad_schwalbach: "kino-im-bad-bad-schwalbach",
  taunussteiner_kinosommer: "taunussteiner-kinosommer",
  union_filmtheater_schneeberg: "union-filmtheater-schneeberg",
  metropol_comma_draussen: "metropol-comma-draussen",
  open_air_baden_baden: "open-air-baden-baden",
  open_air_kino_im_zoo_osnabrueck: "open-air-kino-im-zoo-osnabrueck",
  open_air_kino_langen: "open-air-kino-langen",
  sommer_filmfest_beratzhausen: "sommer-filmfest-beratzhausen",
  sommernachtskino_open_air_geislingen: "sommernachtskino-open-air-geislingen",
  psd_bank_sommerkino: "psd-bank-sommerkino",
  projekt_cinema_central: "projekt-cinema-central",
  dillenburger_open_air_kino: "dillenburger-open-air-kino",
  cineradoplex_freising: "cineradoplex-freising",
  utopolis_multiplex_kino_coburg: "utopolis-multiplex-kino-coburg",
  kitt_tettnang: "kitt-tettnang",
  freiluftkino_inselat_atelier_gardens: "freiluftkino-inselat-atelier-gardens",
  open_air_gernsbach: "open-air-gernsbach",
  open_air_kino_am_wasserschloss_schliengen:
    "open-air-kino-am-wasserschloss-schliengen",
  open_air_kino_in_neuenburg: "open-air-kino-in-neuenburg",
  open_air_burg_frankenberg_aachen: "open-air-burg-frankenberg-aachen",
  kino_am_campus_esslingen: "kino-am-campus-esslingen",
  traumpalast_testkino: "traumpalast-testkino",
  open_air_im_kurpark_badenweiler: "open-air-im-kurpark-badenweiler",
  regina_filmtheater_regensburg: "regina-filmtheater-regensburg",
  studiokino_ratingen: "studiokino-ratingen",
  loe_studios_in_marl: "loe-studios-in-marl",
  cinestar_by_filmpalast_kassel: "cinestar-by-filmpalast-kassel",
  cinemaxx: "cinemaxx",
  apollo_cinemas_multiplex_gelsenkirchen:
    "apollo-cinemas-multiplex-gelsenkirchen",
  cineparc_die_burg: "cineparc-die-burg",
  zuckerfabrik_kinopark_halberstadt: "zuckerfabrik-kinopark-halberstadt",
  park_theater_in_luedenscheid: "park-theater-in-luedenscheid",
  kinopark_aalen: "kinopark-aalen",
  metroplex_fuerth: "metroplex-fuerth",
  cineradoplex_pfaffenhofen: "cineradoplex-pfaffenhofen",
  astra_filmpalast: "astra-filmpalast",
  movietown_cinemas_hoppstaedten_weiersbach:
    "movietown-cinemas-hoppstaedten-weiersbach",
  regina_2000_filmtheater_ellwangen: "regina-2000-filmtheater-ellwangen",
  euromax_cinemas_kerpen: "euromax-cinemas-kerpen",
  cineplex: "cineplex",
  central_kino_center: "central-kino-center",
  pab_kinocenter: "pab-kinocenter",
  scala: "scala",
  capitol_kinocenter_ansbach: "capitol-kinocenter-ansbach",
  filmpalast_salzwedel: "filmpalast-salzwedel",
  cine_chiemgau_traunreut: "cine-chiemgau-traunreut",
  kino_universum_backnang: "kino-universum-backnang",
  movieworld: "movieworld",
  kino_center_heidenheim: "kino-center-heidenheim",
  schauburg_cineworld: "schauburg-cineworld",
  central_theater_uelzen: "central-theater-uelzen",
  weltbio_kino_center_schweinfurt: "weltbio-kino-center-schweinfurt",
  scala_kino: "scala-kino",
  cineplanet_tirschenreuth: "cineplanet-tirschenreuth",
  lichtblick_filmtheater_heide: "lichtblick-filmtheater-heide",
  schauburg_filmtheater: "schauburg-filmtheater",
  filmforum_schwedt: "filmforum-schwedt",
  cineplanet_marktredwitz: "cineplanet-marktredwitz",
  kinopalast_im_rheincenter: "kinopalast-im-rheincenter",
  schauburg_filmpalast_gelsenkirchen: "schauburg-filmpalast-gelsenkirchen",
  filmcenter_dillingen: "filmcenter-dillingen",
  movieworld_kino: "movieworld-kino",
  cinemahlen: "cinemahlen",
  cinema_64_movie_and_more: "cinema-64-movie-and-more",
  kinowelt_worms: "kinowelt-worms",
  movietown_eichsfeld: "movietown-eichsfeld",
  central_kino_in_wittenberg: "central-kino-in-wittenberg",
  zeise_kinos_hamburg: "zeise-kinos-hamburg",
  kinopalast: "kinopalast",
  cinema_filmpalais_dingolfing: "cinema-filmpalais-dingolfing",
  kino_blaue_bruecke: "kino-blaue-bruecke",
  lichtburg_center_dinslaken: "lichtburg-center-dinslaken",
  roxy_holzminden: "roxy-holzminden",
  capitol_kino_lohne: "capitol-kino-lohne",
  nickel_odeon_kino_center_aue_old: "nickel-odeon-kino-center-aue-old",
  cineparc_kinozentrum_frauentor: "cineparc-kinozentrum-frauentor",
  cine_world_cham: "cine-world-cham",
  capitol_heidenheim: "capitol-heidenheim",
  capitol_cinema_center_werne: "capitol-cinema-center-werne",
  union_kino: "union-kino",
  kelheimer_lichtspiele: "kelheimer-lichtspiele",
  kinocenter_central_cineworld_diepholz:
    "kinocenter-central-cineworld-diepholz",
  casablanca_filmtheater: "casablanca-filmtheater",
  domstadtkino_merseburg: "domstadtkino-merseburg",
  roxy_kino: "roxy-kino",
  manhattan_kino: "manhattan-kino",
  cinepark_kino_schrobenhausen: "cinepark-kino-schrobenhausen",
  bali_kino_center_cuxhaven: "bali-kino-center-cuxhaven",
  hofgarten_kino: "hofgarten-kino",
  drive_in_autokino_muenchen: "drive-in-autokino-muenchen",
  drive_in_autokino_frankfurt_gravenbruch:
    "drive-in-autokino-frankfurt-gravenbruch",
  kleines_theater_schillerstrasse_geesthacht:
    "kleines-theater-schillerstrasse-geesthacht",
  mosel_kino: "mosel-kino",
  prestige_filmtheater_kuenzelsau: "prestige-filmtheater-kuenzelsau",
  kino_center_kehl: "kino-center-kehl",
  roxy_filmtheater_heinsberg_alt: "roxy-filmtheater-heinsberg-alt",
  cinema_muenster: "cinema-muenster",
  filmhof_hoya: "filmhof-hoya",
  drive_in_autokino_suttgart: "drive-in-autokino-suttgart",
  apollo_kino_arnsberg_neheim: "apollo-kino-arnsberg-neheim",
  kino_center_anklam: "kino-center-anklam",
  residenz_theater_kino: "residenz-theater-kino",
  lichtburg_kinos: "lichtburg-kinos",
  cinemaja: "cinemaja",
  rosenhof_lichtspiele: "rosenhof-lichtspiele",
  cadillac_veranda_kino_muenchen: "cadillac-veranda-kino-muenchen",
  central_kino_arnsberg_neheim: "central-kino-arnsberg-neheim",
  drive_in_autokino_koeln: "drive-in-autokino-koeln",
  loewenlichtspiele_wallduern: "loewenlichtspiele-wallduern",
  albrecht_kino: "albrecht-kino",
  babylon: "babylon",
  kino_steinfurt: "kino-steinfurt",
  cincinnati_kino: "cincinnati-kino",
  studio_kinos_willingen: "studio-kinos-willingen",
  obscura_filmtheater: "obscura-filmtheater",
  lichtblick_inselkino_norddorf_amrum: "lichtblick-inselkino-norddorf-amrum",
  drive_in_autokino_essen: "drive-in-autokino-essen",
  kino_brakel: "kino-brakel",
  eifelflimmern_autokino_daun: "eifelflimmern-autokino-daun",
  eifel_kino_center_pruem: "eifel-kino-center-pruem",
  park_kino_bad_reichenhall: "park-kino-bad-reichenhall",
  krone_theater: "krone-theater",
  kino_center_rhein_ahr: "kino-center-rhein-ahr",
  neues_rex_filmtheater: "neues-rex-filmtheater",
  gloria_filmpalast_erkelenz_old: "gloria-filmpalast-erkelenz_old",
  apollo_kino_cochem: "apollo-kino-cochem",
  ringdegkino: "ringdegkino",
  apollo_service_kino_altena: "apollo-service-kino-altena",
  utopia_kino_wasserburg: "utopia-kino-wasserburg",
  filmhaus: "filmhaus",
  rex_kino_center: "rex-kino-center",
  brennessel_programmkino: "brennessel-programmkino",
  lichtspielhaus_riedlingen: "lichtspielhaus-riedlingen",
  central_theater: "central-theater",
  neue_post_lichtspiele: "neue-post-lichtspiele",
  neues_rottmann_kino: "neues-rottmann-kino",
  universum_e_v_bramsche: "universum-e-v-bramsche",
  lili_servicekino: "lili-servicekino",
  filmhaus_saarbruecken: "filmhaus-saarbruecken",
  cine_k_oldenburg: "cine-k-oldenburg",
  else_lichtspiele: "else-lichtspiele",
  joki_kino_bad_krozingen: "joki-kino-bad-krozingen",
  kino_51_stufen: "kino-51-stufen",
  kino_im_rathaus: "kino-im-rathaus",
  kino_hotel_meyer_harsefeld: "kino-hotel-meyer-harsefeld",
  ries_theater: "ries-theater",
  lichtspiele_grosshabersdorf_kino_zum_wohlfuehlen:
    "lichtspiele-grosshabersdorf-kino-zum-wohlfuehlen",
  filmeck_demmin: "filmeck-demmin",
  metropolis_kino_im_hauptbahnhof_bochum:
    "metropolis-kino-im-hauptbahnhof-bochum",
  cinema_twistringen: "cinema-twistringen",
  kino_nea: "kino-nea",
  starlight: "starlight",
  gronauer_lichtspiele: "gronauer-lichtspiele",
  ufer_palast: "ufer-palast",
  v_filmforum: "v-filmforum",
  lichtspiel_schneverdingen: "lichtspiel-schneverdingen",
  kinowerkstatt: "kinowerkstatt",
  studio_kino_lounge: "studio-kino-lounge",
  lamm_lichtspiele_erlangen: "lamm-lichtspiele-erlangen",
  kino_museum: "kino-museum",
  filmkunstfest: "filmkunstfest",
  filmfestspiele: "filmfestspiele",
  autokino_meppen: "autokino-meppen",
  filmpassage_muelheim: "filmpassage-muelheim",
  "open.air.schiefererlebnis.dormettingen":
    "open.air.schiefererlebnis.dormettingen",
  open_air_gammertingen: "open-air-gammertingen",
  open_air_peissnitz_halle: "open-air-peissnitz-halle",
  universum_kinocenter_landau: "universum-kinocenter-landau",
  open_air_kino_mosbach: "open-air-kino-mosbach",
  open_air_kino_buchen: "open-air-kino-buchen",
  autokino_carstival_mannheim: "autokino-carstival-mannheim",
  theater_ansbach: "theater-ansbach",
  autokino_taucha: "autokino-taucha",
  cinedrom_donauwoerth: "cinedrom-donauwoerth",
  novum_kino_buedingen: "novum-kino-buedingen",
  open_air_kino_aalen: "open-air-kino-aalen",
  kinopalast_vulkaneifel_daun: "kinopalast-vulkaneifel-daun",
  primus_kinocenter_eschweiler: "primus-kinocenter-eschweiler",
  spreekino_spremberg: "spreekino-spremberg",
  nickel_odeon_kino_center_aue: "nickel-odeon-kino-center-aue",
  kurhaus_kino: "kurhaus-kino",
  gustav_adolf_gedaechtniskirche_nuernberg:
    "gustav-adolf-gedaechtniskirche-nuernberg",
  loe_open_air_kino_marl: "loe-open-air-kino-marl",
  autokino_offenburg: "autokino-offenburg",
  autokino_drive_park_duesseldorf: "autokino-drive-park-duesseldorf",
  ring_theater: "ring-theater",
  park_theater: "park-theater",
  dersa_kino_soltau: "dersa-kino-soltau",
  broadway_wertheim: "broadway-wertheim",
  odeon_kino_center_merzig: "odeon-kino-center-merzig",
  schwali_kino_deggendorf: "schwali-kino-deggendorf",
  roadshow_filmpalast_in_waldbroel: "roadshow-filmpalast-in-waldbroel",
  autokino_am_flughafen_paderborn: "autokino-am-flughafen-paderborn",
  autokino_kassel: "autokino-kassel",
  autokino_bonn: "autokino-bonn",
  autokino_boeblingen: "autokino-boeblingen",
  universum_open_air_bramsche: "universum-open-air-bramsche",
  wissensstadt_sommerkino_berlin: "wissensstadt-sommerkino-berlin",
  olympia_kino_winnenden: "olympia-kino-winnenden",
  kronenlichtspiele: "kronenlichtspiele",
  kino_scala_buellingen: "kino-scala-buellingen",
  autokino_landau: "autokino-landau",
  sommernachtskino_leonberg: "sommernachtskino-leonberg",
  autokino_muelheim: "autokino-muelheim",
  univary_autokino_erfurt: "univary-autokino-erfurt",
  autokino_blieskastel: "autokino-blieskastel",
  autokino_landsweiler: "autokino-landsweiler",
  autokino_voelklingen: "autokino-voelklingen",
  autokino_ffb_fuerstenfeldbruck: "autokino-ffb-fuerstenfeldbruck",
  kultursommer_lueneburg_autokino: "kultursommer-lueneburg-autokino",
  soester_autokino_am_flugplatz: "soester-autokino-am-flugplatz",
  autokino_unter_freiem_himmel_neumarkt:
    "autokino-unter-freiem-himmel-neumarkt",
  filmtheater_worbis: "filmtheater-worbis",
  autokino_hagen: "autokino-hagen",
  autokino_wuppertal: "autokino-wuppertal",
  autokino_hechingen: "autokino-hechingen",
  autokino_waldshut: "autokino-waldshut",
  open_air_arena_homberg: "open-air-arena-homberg",
  autokino_allgaeu: "autokino-allgaeu",
  autokino_mainz: "autokino-mainz",
  autokino_doebeln: "autokino-doebeln",
  autokino_open_air_kemnath: "autokino-open-air-kemnath",
  autokuki_bad_segeberg: "autokuki-bad-segeberg",
  open_air_filmsommer_weimar: "open-air-filmsommer-weimar",
  autokino_hamm: "autokino-hamm",
  autokino_essen: "autokino-essen",
  autokino_tuebingen: "autokino-tuebingen",
  ulmer_autokino: "ulmer-autokino",
  autokino_ettlingen: "autokino-ettlingen",
  autokino_dormagen: "autokino-dormagen",
  autokino_speyer: "autokino-speyer",
  autokino_messe_friedrichshafen: "autokino-messe-friedrichshafen",
  autokino_dessau: "autokino-dessau",
  kino_im_hoefle: "kino-im-hoefle",
  kino_in_der_dampfsaeg_sontheim: "kino-in-der-dampfsaeg-sontheim",
  kuki_zelt_schluechtern: "kuki-zelt-schluechtern",
  autokino_gersthofen: "autokino-gersthofen",
  autokino_apolda: "autokino-apolda",
  autokino_stendal: "autokino-stendal",
  olympia_kino_bietigheim_bissingen: "olympia-kino-bietigheim-bissingen",
  roxy_renaissance_cinema: "roxy-renaissance-cinema",
  open_air_im_kurpark_bad_schwalbach: "open-air-im-kurpark-bad-schwalbach",
  roof_top_cinema_berlin: "roof-top-cinema-berlin",
  autokino_schorndorf: "autokino-schorndorf",
  univary_autokino_hohenfelden: "univary-autokino-hohenfelden",
  lausitzer_autokinofestival_cottbus: "lausitzer-autokinofestival-cottbus",
  autokino_movie_star: "autokino-movie-star",
  univary_autokino_torgau: "univary-autokino-torgau",
  univary_autokino_eventkino_schleiz: "univary-autokino-eventkino-schleiz",
  autokino_oberndorf: "autokino-oberndorf",
  open_air_auf_der_bismarckhoehe: "open-air-auf-der-bismarckhoehe",
  autokino_rennbahn_bielefeld: "autokino-rennbahn-bielefeld",
  autokino_jena: "autokino-jena",
  autokino_crailsheim: "autokino-crailsheim",
  autokino_werne: "autokino-werne",
  autokino_taunusstein: "autokino-taunusstein",
  autokino_menden: "autokino-menden",
  autokino_bamberg: "autokino-bamberg",
  kino_wurzbach: "kino-wurzbach",
  autokino_laichingen: "autokino-laichingen",
  autokino_aschersleben: "autokino-aschersleben",
  gloria_autokino_geislingen: "gloria-autokino-geislingen",
  entertainment_park_io: "entertainment-park-io",
  autokino_im_wildpark_bad_mergentheim: "autokino-im-wildpark-bad-mergentheim",
  schiltacher_open_air_kino: "schiltacher-open-air-kino",
  autokino_strassfurt: "autokino-strassfurt",
  autokinoarena_olfen: "autokinoarena-olfen",
  autokino_schwaebisch_gmuend: "autokino-schwaebisch-gmuend",
  waeller_autokino_altenkirchen: "waeller-autokino-altenkirchen",
  autokino_700_hellenthal: "autokino-700-hellenthal",
  autokino_hoechstadt_an_der_aisch: "autokino-hoechstadt-an-der-aisch",
  filmpalette_jever: "filmpalette-jever",
  autokino_celle: "autokino-celle",
  autokino_wertheim: "autokino-wertheim",
  autokino_backnang: "autokino-backnang",
  drive_in_arena_warstein: "drive-in-arena-warstein",
  autokino_herne: "autokino-herne",
  autokino_willich: "autokino-willich",
  autokino_schlangen: "autokino-schlangen",
  autokino_oelde: "autokino-oelde",
  autokino_herzfeld: "autokino-herzfeld",
  autokino_buenderlichtspiele_buende: "autokino-buenderlichtspiele-buende",
  autokino_rodewald: "autokino-rodewald",
  scenic_autokino_gudensberg: "scenic-autokino-gudensberg",
  autokino_weingarten: "autokino-weingarten",
  autokino_vogelsang: "autokino-vogelsang",
  "auto.kultur_kino_vaihingen": "auto.kultur-kino-vaihingen",
  autokino_eisenhüttenstadt: "autokino-eisenhüttenstadt",
  autokino_waiblingen: "autokino-waiblingen",
  freiluftkino_pompeji_open_air_am_ostkreuz_berlin:
    "freiluftkino-pompeji-open-air-am-ostkreuz-berlin",
  nuertinger_kulturbuehne_open_air_kino:
    "nuertinger-kulturbuehne-open-air-kino",
  autokino_haan: "autokino-haan",
  autokino_ankum: "autokino-ankum",
  autokino_bad_homburg: "autokino-bad-homburg",
  autokino_hilden: "autokino-hilden",
  "autokino_burgenkino_schlitz ": "autokino-burgenkino-schlitz ",
  autokino_auerbach: "autokino-auerbach",
  autokino_limbach_oberfronah: "autokino-limbach-oberfronah",
  harsefelder_lichtspiele_autokino_2020_harsefeld:
    "harsefelder-lichtspiele-autokino-2020-harsefeld",
  paradies_kino_bietigheim_bissingen: "paradies-kino-bietigheim-bissingen",
  autokino_an_der_halloren_schokoladenfabrik:
    "autokino-an-der-halloren-schokoladenfabrik",
  autokino_auggen: "autokino-auggen",
  autokino_am_gueterbahnhof_lsz: "autokino-am-gueterbahnhof-lsz",
  nordeutsches_autokino_ratzeburg: "nordeutsches-autokino-ratzeburg",
  auto_und_eventkino_jueterbog: "auto-und-eventkino-jueterbog",
  open_air_kino_im_stadtpark_burgdorf: "open-air-kino-im-stadtpark-burgdorf",
  autokino_bad_arolsen: "autokino-bad-arolsen",
  moving_history: "moving-history",
  autokino_wernigerode: "autokino-wernigerode",
  autokino_wittlich: "autokino-wittlich",
  autokino_moeckern: "autokino-moeckern",
  univary_autokino_zingst: "univary-autokino-zingst",
  autokino_bad_brueckenau: "autokino-bad-brueckenau",
  "Cinewood Drive In Autokino Waldkraiburg":
    "Cinewood Drive In Autokino Waldkraiburg",
  b_o_campus_aibvision_open_air: "b-o-campus-aibvision-open-air",
  filmtheater_capitol: "filmtheater-capitol",
  hollywood_am_inn: "hollywood-am-inn",
  kieswerk_open_air_kino_weil_am_rhein: "kieswerk-open-air-kino-weil-am-rhein",
  stadtkino_trostberg: "stadtkino-trostberg",
  open_air_im_ochsenzwinger: "open-air-im-ochsenzwinger",
  improtheater: "improtheater",
  open_air_kino_heidenheim: "open-air-kino-heidenheim",
  open_air_kino_tour_bw: "open-air-kino-tour-bw",
  volksbank_luebbecker_land_open_air_kino:
    "volksbank-luebbecker-land-open-air-kino",
  burgkino_erkelenz: "burgkino-erkelenz",
  lvz_sommerkino_im_scheibenholz: "lvz-sommerkino-im-scheibenholz",
  altes_kino: "altes-kino",
  psd_bank_popup_kino: "psd-bank-popup-kino",
  movie_star_parchim: "movie-star-parchim",
  spektrum_art_science_community_berlin:
    "spektrum-art-science-community-berlin",
  filminitiative_wuerzburg: "filminitiative-wuerzburg",
  cinebaar_donaueschingen: "cinebaar-donaueschingen",
  nuit_de_la_glisse: "nuit-de-la-glisse",
  sparkassen_arena_kiel: "sparkassen-arena-kiel",
  w1_kulturzentrum_regensburg: "w1-kulturzentrum-regensburg",
  kino_und_bar_in_der_koenigstadt_berlin:
    "kino-und-bar-in-der-koenigstadt-berlin",
  autokino_rees: "autokino-rees",
  autokino_rahden: "autokino-rahden",
  cinedrive_moenchengladbach: "cinedrive-moenchengladbach",
  autokino_karlsruhe: "autokino-karlsruhe",
  auto_und_open_air_kino_astoria: "auto-und-open-air-kino-astoria",
  open_air_parkbuehne_leipzig: "open-air-parkbuehne-leipzig",
  open_air_kino_hahnenkammsee: "open-air-kino-hahnenkammsee",
  sommerwiese_konstanz: "sommerwiese-konstanz",
  kulturhaus_caserne_friedrichshafen: "kulturhaus-caserne-friedrichshafen",
  open_air_kino_im_parktheater: "open-air-kino-im-parktheater",
  open_air_kino_in_harsefeld: "open-air-kino-in-harsefeld",
  open_air_kino_amphitheater_am_stausee_kelbra:
    "open-air-kino-amphitheater-am-stausee-kelbra",
  kinocenter_open_air_in_haslach: "kinocenter-open-air-in-haslach",
  lausitzer_autokinofestival_cottbus_605b2b4442b51:
    "lausitzer-autokinofestival-cottbus-605b2b4442b51",
  picknick_kino_karlsruhe: "picknick-kino-karlsruhe",
  openair_freibad_walsheim: "openair-freibad-walsheim",
  sommernachtskino_freibad_sindelfingen:
    "sommernachtskino-freibad-sindelfingen",
  open_air_kino_schoenau: "open-air-kino-schoenau",
  filmnaechte_dortmund_autokino: "filmnaechte-dortmund-autokino",
  open_air_kino_im_eichwald_muellheim: "open-air-kino-im-eichwald-muellheim",
  mathaeser_filmpalast: "mathaeser-filmpalast",
  cinestar: "cinestar",
  uci_kinowelt_ruhr_park: "uci-kinowelt-ruhr-park",
  cinedom: "cinedom",
  cinestar_kristall_palast: "cinestar-kristall-palast",
  cinestar_metropolis: "cinestar-metropolis",
  ufa_palast: "ufa-palast",
  dietrich_theater: "dietrich-theater",
  cinemaxx_hannover_raschplatz: "cinemaxx-hannover-raschplatz",
  cinestar_chemnitz_am_roten_turm: "cinestar-chemnitz-am-roten-turm",
  cinespace: "cinespace",
  cinestar_berlin_cubix_am_alexanderplatz:
    "cinestar-berlin-cubix-am-alexanderplatz",
  kinopolis: "kinopolis",
  uci_kinowelt: "uci-kinowelt",
  cinemaxx_charlottencenter: "cinemaxx-charlottencenter",
  cineplex_berlin_in_den_neukoelln_acarden:
    "cineplex-berlin-in-den-neukoelln-acarden",
  cinestar_berlin_tegel: "cinestar-berlin-tegel",
  cinestar_berlin_treptower_park: "cinestar-berlin-treptower-park",
  cineworld_cineplex: "cineworld-cineplex",
  cinemaxx_hamburg_dammtor: "cinemaxx-hamburg-dammtor",
  c1_cinema: "c1-cinema",
  ufa_kristallpalast: "ufa-kristallpalast",
  uci_kinowelt_othmarschen_park: "uci-kinowelt-othmarschen-park",
  cineplex_kinopark_aachen: "cineplex-kinopark-aachen",
  uci_kinowelt_hh_wandsbek: "uci-kinowelt-hh-wandsbek",
  uci_kinowelt_nova_eventis_saale_park: "uci-kinowelt-nova-eventis-saale-park",
  kinopolis_giessen: "kinopolis-giessen",
  uci_kinowelt_mundsburg: "uci-kinowelt-mundsburg",
  uci_kinowelt_am_lausitzpark: "uci-kinowelt-am-lausitzpark",
  cineplex_alhambra: "cineplex-alhambra",
  uci_kinowelt_am_eastgate: "uci-kinowelt-am-eastgate",
  cinemaxx_hamburg_harburg: "cinemaxx-hamburg-harburg",
  cineplex_titania_palast: "cineplex-titania-palast",
  cinetech: "cinetech",
  cineplex_capitol: "cineplex-capitol",
  cinemaxx_berlin_potsdamer_platz: "cinemaxx-berlin-potsdamer-platz",
  zoo_palast: "zoo-palast",
  prisma_cinema_halle: "prisma-cinema-halle",
  cinemaxx_an_der_liederhalle: "cinemaxx-an-der-liederhalle",
  cinestar_berlin_hellersdorf: "cinestar-berlin-hellersdorf",
  cinemaxx_stuttgart_si_centrum: "cinemaxx-stuttgart-si-centrum",
  cinetech_das_erlebniskino: "cinetech-das-erlebniskino",
  cinestar_luebeck_stadthalle: "cinestar-luebeck-stadthalle",
  cineplex_im_bodensee_center: "cineplex-im-bodensee-center",
  cineplex_galleria: "cineplex-galleria",
  union_filmtheater: "union-filmtheater",
  uci_kinowelt_gropius_passagen: "uci-kinowelt-gropius-passagen",
  cineworld: "cineworld",
  filmwelt_gruenstadt: "filmwelt-gruenstadt",
  cineplex_planie: "cineplex-planie",
  cinecitta: "cinecitta",
  cineplex_neumuenster: "cineplex-neumuenster",
  luxor_filmpalast_bensheim: "luxor-filmpalast-bensheim",
  maxx: "maxx",
  filmpalast_cine_world: "filmpalast-cine-world",
  harmonie: "harmonie",
  cineplex_berlin_spandau: "cineplex-berlin-spandau",
  luxor_filmpalast: "luxor-filmpalast",
  cinemaxx_hamburg_wandsbek: "cinemaxx-hamburg-wandsbek",
  e_kinos: "e-kinos",
  bali_kino_palast: "bali-kino-palast",
  citydom: "citydom",
  comet_kinocenter: "comet-kinocenter",
  focus_cinemas: "focus-cinemas",
  citykino: "citykino",
  filmwelt_herne: "filmwelt-herne",
  mega_movies: "mega-movies",
  kammer_lichtspiele: "kammer-lichtspiele",
  cineplex_metropolis: "cineplex-metropolis",
  capitol_filmtheater: "capitol-filmtheater",
  cinestar_capitol_filmpalast: "cinestar-capitol-filmpalast",
  kinopolis_main_taunus: "kinopolis-main-taunus",
  cineplex_apollo_kino_center: "cineplex-apollo-kino-center",
  thomas_filmtheater: "thomas-filmtheater",
  blue_boxx_kino: "blue-boxx-kino",
  lux_kinos: "lux-kinos",
  kinopolis_rhein_neckar: "kinopolis-rhein-neckar",
  kino_movie_star: "kino-movie-star",
  universum_city: "universum-city",
  cineplex_eden_palast: "cineplex-eden-palast",
  citydome: "citydome",
  cineplex_bad_hersfeld: "cineplex-bad-hersfeld",
  alpenfilmtheater: "alpenfilmtheater",
  kinos_am_bahnhof: "kinos-am-bahnhof",
  kino_metropolis: "kino-metropolis",
  "roxy_kinos_neustadt_an.der_weinstrasse":
    "roxy-kinos-neustadt-an.der-weinstrasse",
  kino_am_raschplatz: "kino-am-raschplatz",
  cineplex_cinema_studio_center: "cineplex-cinema-studio-center",
  cine_city: "cine-city",
  kinocenter_eggenfelden: "kinocenter-eggenfelden",
  central_city_cinemas: "central-city-cinemas",
  friedrichsbau_lichtspiele: "friedrichsbau-lichtspiele",
  capitol_theater: "capitol-theater",
  dersa_kino_center: "dersa-kino-center",
  hansa_filmstudio: "hansa-filmstudio",
  apollo_kino_center: "apollo-kino-center",
  casablanca_programmkino: "casablanca-programmkino",
  cinetower_kinopark: "cinetower-kinopark",
  cineplex_thalia_hollywood_filmtheater:
    "cineplex-thalia-hollywood-filmtheater",
  rex_kinos: "rex-kinos",
  cineplex_schlosstheater: "cineplex-schlosstheater",
  camera_zwo_das_arthouse_kino: "camera-zwo-das-arthouse-kino",
  gloria_kino_center: "gloria-kino-center",
  corso_kino_radevormwald: "corso-kino-radevormwald",
  filmbuehne: "filmbuehne",
  kino_buedingen: "kino-buedingen",
  residenz_astor_film_lounge: "residenz-astor-film-lounge",
  cine_circus: "cine-circus",
  cinetech_open_air_kino: "cinetech-open-air-kino",
  lichtspielhaus_lennestadt: "lichtspielhaus-lennestadt",
  holi_kino: "holi-kino",
  kultiplex_kinocenter: "kultiplex-kinocenter",
  regina_metropolis_filmtheater: "regina-metropolis-filmtheater",
  weidenhof: "weidenhof",
  kino_neue_filmbuehne: "kino-neue-filmbuehne",
  arri_kino: "arri-kino",
  capitol_lichtspiele: "capitol-lichtspiele",
  aibvision_filmtheater: "aibvision-filmtheater",
  rex_lichtspiele_am_ring: "rex-lichtspiele-am-ring",
  kinocenter_stadthagen: "kinocenter-stadthagen",
  ali_kinocenter: "ali-kinocenter",
  residenz_kinocenter: "residenz-kinocenter",
  rex_kino: "rex-kino",
  oho_kinocenter: "oho-kinocenter",
  kinocenter_schwelm: "kinocenter-schwelm",
  kino_utopolis: "kino-utopolis",
  stadtsaal_lichtspiele: "stadtsaal-lichtspiele",
  kinocenter_capitol: "kinocenter-capitol",
  cinepark: "cinepark",
  forum_rothenburg: "forum-rothenburg",
  schauburg: "schauburg",
  cine_greth: "cine-greth",
  thalia_kino: "thalia-kino",
  neue_schauburg: "neue-schauburg",
  luna_theater: "luna-theater",
  ct_lichtspiele_kino: "ct-lichtspiele-kino",
  kinocenter_biber: "kinocenter-biber",
  kino_im_kulturhaus: "kino-im-kulturhaus",
  movieplexx_delhi_center_kino: "movieplexx-delhi-center-kino",
  omaha_film: "omaha-film",
  schukurama_kino: "schukurama-kino",
  kino_breitwand: "kino-breitwand",
  kino_saulgau: "kino-saulgau",
  filmburg: "filmburg",
  metropolis_kino_nuernberg: "metropolis-kino-nuernberg",
  bambi_filmstudio: "bambi-filmstudio",
  filmstation: "filmstation",
  mephisto_kino_ulm: "mephisto-kino-ulm",
  olympia_filmtheater: "olympia-filmtheater",
  filmzentrum_am_rathaus: "filmzentrum-am-rathaus",
  neues_regina: "neues-regina",
  schiller_lichtspiele: "schiller-lichtspiele",
  lichtspiel_und_kunsttheater_schauburg:
    "lichtspiel-und-kunsttheater-schauburg",
  corso_kino: "corso-kino",
  "scala_warendorf.de": "scala-warendorf.de",
  erbacher_lichtspiele: "erbacher-lichtspiele",
  kino_linden_theater: "kino-linden-theater",
  altstadtkinos_union: "altstadtkinos-union",
  studiokino: "studiokino",
  kinowelt_am_ammersee: "kinowelt-am-ammersee",
  filmforum: "filmforum",
  capitol_kino_center: "capitol-kino-center",
  hochhaus_lichtspiele: "hochhaus-lichtspiele",
  metropol_theater: "metropol-theater",
  kino_grimm: "kino-grimm",
  zoom: "zoom",
  cinema_filmtheater: "cinema-filmtheater",
  cineplex_adria_filmtheater_steglitz: "cineplex-adria-filmtheater-steglitz",
  sendlinger_tor_filmtheater: "sendlinger-tor-filmtheater",
  schaubuehne_lindenfels: "schaubuehne-lindenfels",
  kinocenter_ratingen: "kinocenter-ratingen",
  forum_22: "forum-22",
  pro_winzkino: "pro-winzkino",
  kino_im_grossen_kurhaus: "kino-im-grossen-kurhaus",
  filmbuehne_caligari: "filmbuehne-caligari",
  cineroyal: "cineroyal",
  viktoria_filmtheater: "viktoria-filmtheater",
  kino_in_der_lagerhalle: "kino-in-der-lagerhalle",
  eva_lichtspiele: "eva-lichtspiele",
  mephisto_kino_augsburg: "mephisto-kino-augsburg",
  atelier_kino_im_savoy_theater: "atelier-kino-im-savoy-theater",
  fsk_kino: "fsk-kino",
  kino_im_griesbraeu: "kino-im-griesbraeu",
  cineplex_falkensee_kino_ala: "cineplex-falkensee-kino-ala",
  cosima_filmtheater: "cosima-filmtheater",
  mike_s_kino: "mike-s-kino",
  astoria: "astoria",
  kronen_lichtspiele: "kronen-lichtspiele",
  kinothek: "kinothek",
  groeben_lichtspiele: "groeben-lichtspiele",
  puschkino: "puschkino",
  meisengeige: "meisengeige",
  lichtspielhaus: "lichtspielhaus",
  kino_lahnstein: "kino-lahnstein",
  kino_die_birke: "kino-die-birke",
  astor_film_lounge: "astor-film-lounge",
  filmpalette: "filmpalette",
  casino_lichtspiele: "casino-lichtspiele",
  kino_breitwand_im_schloss_seefeld: "kino-breitwand-im-schloss-seefeld",
  filmtheater: "filmtheater",
  cinema_prerow: "cinema-prerow",
  kandelhof_kino: "kandelhof-kino",
  kino_alte_brennerei: "kino-alte-brennerei",
  kino: "kino",
  gloria_palast: "gloria-palast",
  deli_kino: "deli-kino",
  acud_kino: "acud-kino",
  metropolis_programmkino: "metropolis-programmkino",
  kino_kelkheim: "kino-kelkheim",
  subiaco: "subiaco",
  luna_filmtheater: "luna-filmtheater",
  filmstudio_im_alten_stadttheater: "filmstudio-im-alten-stadttheater",
  programmkino_kreml_zollhaus: "programmkino-kreml-zollhaus",
  theatiner_film: "theatiner-film",
  filmtheater_hasetor: "filmtheater-hasetor",
  kino_im_multikulturellen_centrum: "kino-im-multikulturellen-centrum",
  kino_im_waldhorn: "kino-im-waldhorn",
  holzland_kino: "holzland-kino",
  casablanca: "casablanca",
  lichtspiele_moessingen: "lichtspiele-moessingen",
  arsenal: "arsenal",
  sweetsixteen: "sweetsixteen",
  oberstdorfer_kino: "oberstdorfer-kino",
  corso_film_casino: "corso-film-casino",
  luna_lichtspieltheater: "luna-lichtspieltheater",
  filmriss_kino: "filmriss-kino",
  centraltheater_thale: "centraltheater-thale",
  cinema: "cinema",
  studentischer_filmkreis_an_der_tu_darmstadt:
    "studentischer-filmkreis-an-der-tu-darmstadt",
  lichtblick: "lichtblick",
  viktoria_theater: "viktoria-theater",
  kino_eifel_film_buehne: "kino-eifel-film-buehne",
  lichtspiele_hoechst: "lichtspiele-hoechst",
  zentral_theater: "zentral-theater",
  linden_theater: "linden-theater",
  marias_kino: "marias-kino",
  kronberger_lichtspiele: "kronberger-lichtspiele",
  "3001_kino": "3001-kino",
  alabama_kino: "alabama-kino",
  bundesplatz_kino: "bundesplatz-kino",
  lichtspielhaus_und_cinebar: "lichtspielhaus-und-cinebar",
  kino_kiste: "kino-kiste",
  kino_in_der_gems: "kino-in-der-gems",
  lilo_service_filmtheater: "lilo-service-filmtheater",
  koelner_filmhaus: "koelner-filmhaus",
  linden_kino: "linden-kino",
  kino_im_filmmuseum: "kino-im-filmmuseum",
  olympia_kino: "olympia-kino",
  filmstudio_an_der_rwth_aachen: "filmstudio-an-der-rwth-aachen",
  das_kino: "das-kino",
  orfeo_programmkino: "orfeo-programmkino",
  cineplex_metropolis_kinocenter: "cineplex-metropolis-kinocenter",
  filmeck_im_buergerhaus: "filmeck-im-buergerhaus",
  filmmuseum: "filmmuseum",
  union_studio_fuer_filmkunst: "union-studio-fuer-filmkunst",
  kino_koeppern: "kino-koeppern",
  open_air_kino_im_waschhaus: "open-air-kino-im-waschhaus",
  kulturzentrum_pelmke: "kulturzentrum-pelmke",
  tivoli_filmtheater: "tivoli-filmtheater",
  kaisersaal_lichtspiele: "kaisersaal-lichtspiele",
  karlstorkino: "karlstorkino",
  scharfrichter_kino: "scharfrichter-kino",
  kommunales_kino_im_mon_ami: "kommunales-kino-im-mon-ami",
  kommunales_kino_im_alten_wiehrebahnhof:
    "kommunales-kino-im-alten-wiehrebahnhof",
  neues_kino_im_hoersaal: "neues-kino-im-hoersaal",
  lichtspiele: "lichtspiele",
  kinocenter_am_steinweg: "kinocenter-am-steinweg",
  filmforum_hoechst: "filmforum-hoechst",
  kino_anspach: "kino-anspach",
  fabrikkino: "fabrikkino",
  kulturelles_aktionsprojekt: "kulturelles-aktionsprojekt",
  friedrich_wilhelm_murnau_stiftung_filmtheater:
    "friedrich-wilhelm-murnau-stiftung-filmtheater",
  kino_koki_luebeck: "kino-koki-luebeck",
  provinzkino: "provinzkino",
  luru_kino_in_der_spinnerei: "luru-kino-in-der-spinnerei",
  kinocafe_filmkulturhaus: "kinocafe-filmkulturhaus",
  programmkino: "programmkino",
  kino_in_der_brotfabrik: "kino-in-der-brotfabrik",
  kino_cafe_kaszynski: "kino-cafe-kaszynski",
  ostseekino_kühlungsborn: "ostseekino-kühlungsborn",
  engel_lichtspiele: "engel-lichtspiele",
  autokino_langenhessen: "autokino-langenhessen",
  kintopp_filmtheater: "kintopp-filmtheater",
  rhythmus_filmtheater: "rhythmus-filmtheater",
  weltecho: "weltecho",
  zeughauskino: "zeughauskino",
  endstation_kino: "endstation-kino",
  kino_klappe: "kino-klappe",
  cinema_salzgitter_bad: "cinema-salzgitter-bad",
  ostseekino_kamp_theater: "ostseekino-kamp-theater",
  saalbau_lichtspiele: "saalbau-lichtspiele",
  kino_metropol: "kino-metropol",
  kino_in_der_schauburg: "kino-in-der-schauburg",
  e_werk_kino: "e-werk-kino",
  regina_lichtspiele: "regina-lichtspiele",
  kino_achteinhalb: "kino-achteinhalb",
  lichtspieltheater_willich: "lichtspieltheater-willich",
  das_andere_kino: "das-andere-kino",
  filmstudio_kochel: "filmstudio-kochel",
  elite: "elite",
  kinoverein_bordesholm: "kinoverein-bordesholm",
  kinoptikum_programmkino: "kinoptikum-programmkino",
  astor_cinema_lounge: "astor-cinema-lounge",
  kiez_kino: "kiez-kino",
  kunstbauerkino: "kunstbauerkino",
  kommunales_kino_mainspitze: "kommunales-kino-mainspitze",
  cafe_grenzbereiche: "cafe-grenzbereiche",
  kuba: "kuba",
  zazie: "zazie",
  kino_im_theaterstadel: "kino-im-theaterstadel",
  orfeo: "orfeo",
  kino_lichtspiele_wemding: "kino-lichtspiele-wemding",
  kino_in_der_cobra: "kino-in-der-cobra",
  murrlichtspiele: "murrlichtspiele",
  uferpalast: "uferpalast",
  kronenkino: "kronenkino",
  arthaus_kino_im_rheinischen_landesmuseum:
    "arthaus-kino-im-rheinischen-landesmuseum",
  latuecht: "latuecht",
  scala_kultur: "scala-kultur",
  onikon: "onikon",
  studiokino_eisenstein: "studiokino-eisenstein",
  lagerhaus_kino: "lagerhaus-kino",
  kino_am_park: "kino-am-park",
  walzenlagerkino_im_zentrum_altenberg: "walzenlagerkino-im-zentrum-altenberg",
  film_eck: "film-eck",
  kikubi_programmkino: "kikubi-programmkino",
  offkino_klappe_die_zweite: "offkino-klappe-die-zweite",
  blow_up_kino_in_der_kulturfabrik: "blow-up-kino-in-der-kulturfabrik",
  odins_filmtheater: "odins-filmtheater",
  metropolis_filmtheater: "metropolis-filmtheater",
  filmforum_nrw_im_museum_ludwig: "filmforum-nrw-im-museum-ludwig",
  kommkino: "kommkino",
  starlight_kino: "starlight-kino",
  kino_im_hallenbad: "kino-im-hallenbad",
  kommunales_kino_guckloch: "kommunales-kino-guckloch",
  hasetor_das_kulturkino: "hasetor-das-kulturkino",
  club_passage: "club-passage",
  kino_kleine_fluchten_in_der_manufaktur:
    "kino-kleine-fluchten-in-der-manufaktur",
  kino_beck: "kino-beck",
  kulturzentrum_lichtburg: "kulturzentrum-lichtburg",
  kino_im_sprengel: "kino-im-sprengel",
  achteinhalb: "achteinhalb",
  kino_neue_lichtspiele: "kino-neue-lichtspiele",
  kommunales_kino_lichtblick: "kommunales-kino-lichtblick",
  kino_zeli_zeteler_lichtspiele: "kino-zeli-zeteler-lichtspiele",
  hafenkino: "hafenkino",
  cinema_im_leinepark: "cinema-im-leinepark",
  cinemayence: "cinemayence",
  lichtmess_kino: "lichtmess-kino",
  studio_17: "studio-17",
  camillokino: "camillokino",
  steinhaus_im_exil: "steinhaus-im-exil",
  kommunales_kino_im_haus: "kommunales-kino-im-haus",
  kulturfabrik_meda_kino: "kulturfabrik-meda-kino",
  filmnaechte_am_elbufer: "filmnaechte-am-elbufer",
  aka_filmclub_hoersaal_2006_kollegiengebaeude_ii_der_uni_freiburg:
    "aka-filmclub-hoersaal-2006-kollegiengebaeude-ii-der-uni-freiburg",
  freiluftkino_friedrichshain: "freiluftkino-friedrichshain",
  capitol_das_kulturkino: "capitol-das-kulturkino",
  kino_im_kasten: "kino-im-kasten",
  filmforum_im_stadttheater: "filmforum-im-stadttheater",
  harmonie_lichtspiele: "harmonie-lichtspiele",
  kino_alte_muehle: "kino-alte-muehle",
  stadtkino_statt_kino: "stadtkino-statt-kino",
  universum: "universum",
  ritterhuder_lichtspiele: "ritterhuder-lichtspiele",
  kruppa_sven_kino: "kruppa-sven-kino",
  kammerspiele: "kammerspiele",
  freiluftkino_kreuzberg_im_kunstquartier_bethanien:
    "freiluftkino-kreuzberg-im-kunstquartier-bethanien",
  malzhaus: "malzhaus",
  kulturverein_olympiadorf: "kulturverein-olympiadorf",
  eschborn_k: "eschborn-k",
  kino_d_im_buergerhaus: "kino-d-im-buergerhaus",
  landkino: "landkino",
  goli_theater_goch: "goli-theater-goch",
  kino_wolfratshausen: "kino-wolfratshausen",
  kinoinitiative_35: "kinoinitiative-35",
  talflimmern_open_air_kino: "talflimmern-open-air-kino",
  schaustall: "schaustall",
  kommunales_kino_im_forum: "kommunales-kino-im-forum",
  sumpfblume: "sumpfblume",
  kino_im_schafstall: "kino-im-schafstall",
  cinemagnum: "cinemagnum",
  cinemaxx_mannheim: "cinemaxx-mannheim",
  stadtwerke_sommerkino: "stadtwerke-sommerkino",
  fiege_kinoopenair: "fiege-kinoopenair",
  cineplex_goslarer_theater: "cineplex-goslarer-theater",
  primus_palast_film_buehne: "primus-palast-film-buehne",
  corso: "corso",
  universum_kino_palast: "universum-kino-palast",
  eck_s_kino_niebuell: "eck-s-kino-niebuell",
  hochschulfilmclub_der_tu_ilmenau: "hochschulfilmclub-der-tu-ilmenau",
  palatin_filmtheater: "palatin-filmtheater",
  lu_li_kinocenter: "lu-li-kinocenter",
  usk_elsdorf: "usk-elsdorf",
  rex_palast: "rex-palast",
  open_air_kino_vier_linden: "open-air-kino-vier-linden",
  pupille: "pupille",
  loewen_lichtspiele: "loewen-lichtspiele",
  bavaria_kino: "bavaria-kino",
  kur_lichtspiele: "kur-lichtspiele",
  filmwelt: "filmwelt",
  movie_kinocenter_marienberg: "movie-kinocenter-marienberg",
  kino_windlicht: "kino-windlicht",
  filmbuehne_groemitz: "filmbuehne-groemitz",
  filmtheater_badischer_hof: "filmtheater-badischer-hof",
  savoy_kino: "savoy-kino",
  union_theater_plochingen: "union-theater-plochingen",
  phantasia_familienkino_gangkofen: "phantasia-familienkino-gangkofen",
  unifilm_im_audimax: "unifilm-im-audimax",
  kaiserhof_lichtspiele: "kaiserhof-lichtspiele",
  kurtheater_kino: "kurtheater-kino",
  sommerkino_zempin: "sommerkino-zempin",
  kino_wesenberg: "kino-wesenberg",
  kino_nordlicht: "kino-nordlicht",
  open_air_kino_im_kulisse_garten: "open-air-kino-im-kulisse-garten",
  sommerkino_auf_der_feinkost: "sommerkino-auf-der-feinkost",
  cinema_boppard: "cinema-boppard",
  souterrain: "souterrain",
  regenbogenkino: "regenbogenkino",
  engelsburg: "engelsburg",
  kino_bar_oscar: "kino-bar-oscar",
  z_inema_kino: "z-inema-kino",
  gegenlicht_kino: "gegenlicht-kino",
  kommunales_kino_im_capitol: "kommunales-kino-im-capitol",
  kaminwerk: "kaminwerk",
  kleines_kino_in_der_stadt_und_regionalbibliothek:
    "kleines-kino-in-der-stadt-und-regionalbibliothek",
  altstadtkinos_cinema: "altstadtkinos-cinema",
  angerlichtspiele: "angerlichtspiele",
  butzbacher_open_air_kino: "butzbacher-open-air-kino",
  cinema_arthouse: "cinema-arthouse",
  filmclub_mittendrin: "filmclub-mittendrin",
  filmwelt_lippe: "filmwelt-lippe",
  freiluftkino_rehberge: "freiluftkino-rehberge",
  kommunales_kino_im_kuenstlerhaus: "kommunales-kino-im-kuenstlerhaus",
  kult_kinobar: "kult-kinobar",
  open_air_krafftscher_hof: "open-air-krafftscher-hof",
  outdoor_cine_sommerkino_am_wasserturm:
    "outdoor-cine-sommerkino-am-wasserturm",
  schumacher_atlantic_kino: "schumacher-atlantic-kino",
  schunterkino: "schunterkino",
  fabrik_heeder: "fabrik-heeder",
  kino_kaarst: "kino-kaarst",
  kino_im_druckluft: "kino-im-druckluft",
  kino_cafe_trauma: "kino-cafe-trauma",
  naxos_kino_im_theater_willy_praml: "naxos-kino-im-theater-willy-praml",
  kdw_neumuenster: "kdw-neumuenster",
  ostseebad_goehren_kinohalle_regenbogencamp:
    "ostseebad-goehren-kinohalle-regenbogencamp",
  kino_am_wasserturm: "kino-am-wasserturm",
  zeltkino_hiddensee: "zeltkino-hiddensee",
  ajz_kino: "ajz-kino",
  astor_grand_cinema: "astor-grand-cinema",
  lumos_lichtspiele_lounge: "lumos-lichtspiele-lounge",
  seenema_stadtkino_bad_waldsee_eg: "seenema-stadtkino-bad-waldsee-eg",
  wandelhalle_reinhardshausen: "wandelhalle-reinhardshausen",
  cinema_augustinum: "cinema-augustinum",
  clubkino_capitol_lichtenstein: "clubkino-capitol-lichtenstein",
  kino_breitwand_gauting: "kino-breitwand-gauting",
  cineplex_koeln: "cineplex-koeln",
  ferienzentrum_schloss_dankern: "ferienzentrum-schloss-dankern",
  programmkino_lichtblick_e_v: "programmkino-lichtblick-e-v",
  tip_freilichtbuehne_am_weissensee: "tip-freilichtbuehne-am-weissensee",
  open_air_kino_tucherschloss: "open-air-kino-tucherschloss",
  sommernachtskino: "sommernachtskino",
  open_air_zentralgasthof_weinboehla_gmbh:
    "open-air-zentralgasthof-weinboehla-gmbh",
  freilichtkino_melsungen: "freilichtkino-melsungen",
  open_air_marburg: "open-air-marburg",
  arena_schlachthof_open_air: "arena-schlachthof-open-air",
  hillersche_villa_freilichtbuehne_weinau:
    "hillersche-villa-freilichtbuehne-weinau",
  sommernachtskino_schloss_neuhaus: "sommernachtskino-schloss-neuhaus",
  filmarena_open_air_kino_theatervorplatz:
    "filmarena-open-air-kino-theatervorplatz",
  open_air_kino_im_schlosshof_dillingen:
    "open-air-kino-im-schlosshof-dillingen",
  commerz_real_cinema: "commerz-real-cinema",
  herrenberger_sommernachtskino: "herrenberger-sommernachtskino",
  open_air_kino_an_der_sportanlage_schneewinkl_am_koenigssee:
    "open-air-kino-an-der-sportanlage-schneewinkl-am-koenigssee",
  open_air_kino_katharinenruine: "open-air-kino-katharinenruine",
  open_air_im_innenhof_vom_schwarzen_kloster:
    "open-air-im-innenhof-vom-schwarzen-kloster",
  gerniale_kino_open_air: "gerniale-kino-open-air",
  europa_kinos: "europa-kinos",
  inselkino_baltrum: "inselkino-baltrum",
  open_air: "open-air",
  kino_im_oscar_kulturspielhaus: "kino-im-oscar-kulturspielhaus",
  kino_im_zeiss_grossplanetarium_berlin:
    "kino-im-zeiss-grossplanetarium-berlin",
  openair_kino: "openair-kino",
  sommerkino_im_schlosshof: "sommerkino-im-schlosshof",
  regina_filmtheater: "regina-filmtheater",
  uci_kinowelt_nordhorn: "uci-kinowelt-nordhorn",
  kino_in_der_scheune: "kino-in-der-scheune",
  sion_sommerkino: "sion-sommerkino",
  kino_alzenau: "kino-alzenau",
  kino_im_kurtheater: "kino-im-kurtheater",
  ostpassagen_theater: "ostpassagen-theater",
  uci_kinowelt_berlin_mercedes_platz_luxe:
    "uci-kinowelt-berlin-mercedes-platz-luxe",
  astor_film_lounge_hafencity: "astor-film-lounge-hafencity",
  roxy_kitzingen: "roxy-kitzingen",
  cineplex_open_air_kino: "cineplex-open-air-kino",
  conversationshaus_weisser_saal_norderney:
    "conversationshaus-weisser-saal-norderney",
  film_und_kinobuero_hessen: "film-und-kinobuero-hessen",
  deutsches_filminstitut_filmmuseum: "deutsches-filminstitut-filmmuseum",
  freiluftkino_frankfurt_frankfurt_am_main:
    "freiluftkino-frankfurt-frankfurt-am-main",
  open_air_altes_deutsches_gymnasium: "open-air-altes-deutsches-gymnasium",
  open_air_im_seebad_starnberg: "open-air-im-seebad-starnberg",
  sommerkino_auf_der_galopprennbahn_im_scheibenholz:
    "sommerkino-auf-der-galopprennbahn-im-scheibenholz",
  kino_in_dorfen: "kino-in-dorfen",
  schauspielhaus_kulturquartier: "schauspielhaus-kulturquartier",
  cine_k: "cine-k",
  jac_kino_attendorn: "jac-kino-attendorn",
  lichtblick_filmtheater: "lichtblick-filmtheater",
  capitol_theater_gmbh_offenbach: "capitol-theater-gmbh-offenbach",
  film_shop_kassel: "film-shop-kassel",
  raststaette: "raststaette",
  autokino_plus_eberbach_eberbach: "autokino-plus-eberbach-eberbach",
  cinema_bad_saarow: "cinema-bad-saarow",
  kinopalast_eifel_mosel: "kinopalast-eifel-mosel",
  kino_openair_biergarten_im_schutterhof_ingolstadt:
    "kino-openair-biergarten-im-schutterhof-ingolstadt",
  burg_kino_5f328858e8b2a: "burg-kino-5f328858e8b2a",
  arteschock_e_v_lauf: "arteschock-e-v-lauf",
  spektrum_selb_i_kino_kultur_cafe_selb:
    "spektrum-selb-i-kino-kultur-cafe-selb",
  roxy_kino_dortmund: "roxy-kino-dortmund",
  inselkino_spiekeroog: "inselkino-spiekeroog",
  open_air_kino_muellheim: "open-air-kino-muellheim",
  open_air_baden_baden_baden_baden: "open-air-baden-baden-baden-baden",
  charlottenburg_s_bahn_station: "charlottenburg-s-bahn-station",
  scheunenkino_nettersheim_nettersheim: "scheunenkino-nettersheim-nettersheim",
  open_air_kino_haslach_im_kinzigtal: "open-air-kino-haslach-im-kinzigtal",
  ews_sommerkino_schoenau_im_schwarzwald:
    "ews-sommerkino-schoenau-im-schwarzwald",
  open_air_kino_regensburg: "open-air-kino-regensburg",
  rantastic_kaept_n_kino: "rantastic-kaept-n-kino",
  ludwigsburger_sommernachts_open_air_kino:
    "ludwigsburger-sommernachts-open-air-kino",
  donauflimmern_kino_open_air_ingolstadt:
    "donauflimmern-kino-open-air-ingolstadt",
  biennale_altoetting: "biennale-altoetting",
  mobiles_kino_esslingen: "mobiles-kino-esslingen",
  lichter_filmfest_frankfurt_international_frankfurt_am_main:
    "lichter-filmfest-frankfurt-international-frankfurt-am-main",
  kino_alte_muehle_61c0b6a228241: "kino-alte-muehle-61c0b6a228241",
  open_air_an_der_krabatmuehle_schwarzkollm:
    "open-air-an-der-krabatmuehle-schwarzkollm",
  donau_film_sterne: "donau-film-sterne",
  veranstaltungen_vitte: "veranstaltungen-vitte",
  sommernachtskino_open_air_ehrenkirchen:
    "sommernachtskino-open-air-ehrenkirchen",
  corso_kino_62e8dde7378e2: "corso-kino-62e8dde7378e2",
  open_air_travemuende_luebeck: "open-air-travemuende-luebeck",
  filmklubb: "filmklubb",
  open_air_bad_windsbach_gunzenhausen: "open-air-bad-windsbach-gunzenhausen",
  mobile_kino_unterfilm_clubkino: "mobile-kino-unterfilm-clubkino",
  transit_filmfest_regensburg: "transit-filmfest-regensburg",
  filmhaus_heidelberg: "filmhaus-heidelberg",
  campus_kinowelt_wolfen: "campus-kinowelt-wolfen",
  spreeauen_park: "spreeauen-park",
  metzinger_open_air_kino: "metzinger-open-air-kino",
  open_air_kino_bw_eichstetten: "open-air-kino-bw-eichstetten",
  cinefactory: "cinefactory",
  filmtheater_am_sandwall_6480715cbd36a:
    "filmtheater-am-sandwall-6480715cbd36a",
  freiluftkino_frankfurt_innenhof_cantate_saal:
    "freiluftkino-frankfurt-innenhof-cantate-saal",
  the_student_hotel: "the-student-hotel",
  haubentaucher: "haubentaucher",
  mobile_kino_berliner_berg_brauerei: "mobile-kino-berliner-berg-brauerei",
  sommerkino_hameln_im_buergergarten: "sommerkino-hameln-im-buergergarten",
  mobiles_kino_e_v_tucherschloss: "mobiles-kino-e-v-tucherschloss",
  open_air_kino_quickborn: "open-air-kino-quickborn",
  pellerhaus: "pellerhaus",
  museum_fuer_kommunikation: "museum-fuer-kommunikation",
  beim_bast: "beim-bast",
  theater_am_potsdamer_platz: "theater-am-potsdamer-platz",
  open_air_im_freizeitpark_langfort_langenfeld_rheinland:
    "open-air-im-freizeitpark-langfort-langenfeld-rheinland",
  ship_wiesbadeng: "ship-wiesbadeng",
  ship_mainz: "ship-mainz",
  silbersalz_festival: "silbersalz-festival",
  stattkino_65d583735b172: "stattkino-65d583735b172",
  kino_unterm_dach_e_v: "kino-unterm-dach-e-v",
  prestige_kino_frankfurt_am_main: "prestige-kino-frankfurt-am-main",
  kulturkino_kaimt: "kulturkino-kaimt",
  burg_kino: "burg-kino",
  casablanca_kino_kneipe: "casablanca-kino-kneipe",
  clubkino_siegmar: "clubkino-siegmar",
  caligari_kino: "caligari-kino",
  cinema_paradiso: "cinema-paradiso",
  butzbacher_filmtheater: "butzbacher-filmtheater",
  bonner_kinemathek_brotfabrik: "bonner-kinemathek-brotfabrik",
  cineding: "cineding",
  cinematheque_leipzig: "cinematheque-leipzig",
  kino_centraltheater: "kino-centraltheater",
  b_movie: "b-movie",
  centralkino: "centralkino",
  clubkino: "clubkino",
  biesdorfer_parkbuehne: "biesdorfer-parkbuehne",
  kino_spreehoefe: "kino-spreehoefe",
  filmtheater_am_friedrichshain: "filmtheater-am-friedrichshain",
  city_kino: "city-kino",
  kant_kino: "kant-kino",
  mcc_center: "mcc-center",
  metro_kino_im_schlosshof: "metro-kino-im-schlosshof",
  freiluftkino_friedrichshagen: "freiluftkino-friedrichshagen",
  rollberg_kinos: "rollberg-kinos",
  passage_kino: "passage-kino",
  bavaria_kino_center_simbach: "bavaria-kino-center-simbach",
  delphi_filmpalast_am_zoo: "delphi-filmpalast-am-zoo",
  blauer_stern: "blauer-stern",
  yorck_kino: "yorck-kino",
  film_und_kino: "film-und-kino",
  kino_international: "kino-international",
  babylon_kino: "babylon-kino",
  saalbau: "saalbau",
  magazin_filmkunsttheater: "magazin-filmkunsttheater",
  turmpalast: "turmpalast",
  bambi_u_loewenherz_kino: "bambi-u-loewenherz-kino",
  apollo_kino: "apollo-kino",
  kino_traumstern: "kino-traumstern",
  capitol_dahlem: "capitol-dahlem",
  neues_off_kino: "neues-off-kino",
  xenon_kino: "xenon-kino",
  kinobar_prager_fruehling: "kinobar-prager-fruehling",
  thalia_cinema_coffee_and_cigarettes_kino:
    "thalia-cinema-coffee-and-cigarettes-kino",
  mal_seh_n_kino: "mal-seh-n-kino",
  werkstattkino: "werkstattkino",
  holi_filmtheater: "holi-filmtheater",
  schlachthof_kino: "schlachthof-kino",
  fantasia_filmtheater: "fantasia-filmtheater",
  hitch: "hitch",
  cinema_paris: "cinema-paris",
  fontane_klub: "fontane-klub",
  marburger_filmkunsttheater_kammer_palette_atelier_filmtheater:
    "marburger-filmkunsttheater-kammer-palette-atelier-filmtheater",
  cinestar_berlin_sony_center: "cinestar-berlin-sony-center",
  uci_kinowelt_friedrichshain: "uci-kinowelt-friedrichshain",
  frankenheim_kino: "frankenheim-kino",
  haus_der_kulturen_der_welt: "haus-der-kulturen-der-welt",
  urania: "urania",
  freilichtbuehne_burghalde: "freilichtbuehne-burghalde",
  harmonie_lux_kinocenter: "harmonie-lux-kinocenter",
  studio_fuer_filmkunst: "studio-fuer-filmkunst",
  melodie_filmtheater: "melodie-filmtheater",
  festival_kino: "festival-kino",
  gloria_theater: "gloria-theater",
  astoria_palast: "astoria-palast",
  taunus_kinocenter: "taunus-kinocenter",
  studienkreis_film_hzo_20: "studienkreis-film-hzo-20",
  kinoh: "kinoh",
  filmtheater_mitten_im_meer: "filmtheater-mitten-im-meer",
  freiluftkino_museen_dahlem: "freiluftkino-museen-dahlem",
  magic_cinema: "magic-cinema",
  oli_lichtspiele_magdeburg: "oli-lichtspiele-magdeburg",
  skala_kino_center: "skala-kino-center",
  roxy: "roxy",
  union_i_u_ii_filmtheater: "union-i-u-ii-filmtheater",
  stadtkino_kirchheim: "stadtkino-kirchheim",
  berger_kino: "berger-kino",
  klubkino_universitaetskino_in_der_muschel:
    "klubkino-universitaetskino-in-der-muschel",
  kinocenter_die_kurbel: "kinocenter-die-kurbel",
  atlantis_theater: "atlantis-theater",
  thalia_kino_treff: "thalia-kino-treff",
  scala_filmtheater: "scala-filmtheater",
  ut_connewitz: "ut-connewitz",
  bavaria_lichtspiele: "bavaria-lichtspiele",
  metropol_cinema: "metropol-cinema",
  palasttheater: "palasttheater",
  filmgalerie: "filmgalerie",
  filmtheater_am_sandwall: "filmtheater-am-sandwall",
  imax_dome_filmtheater: "imax-dome-filmtheater",
  savoy_und_cinema_am_schwan: "savoy-und-cinema-am-schwan",
  schongau_filmtheater: "schongau-filmtheater",
  pali_kino: "pali-kino",
  camera_lichtspiele: "camera-lichtspiele",
  heli_kino: "heli-kino",
  forum_der_kunst_u_ausstellungshalle_der_bundesrepublik_deutschland:
    "forum-der-kunst-u-ausstellungshalle-der-bundesrepublik-deutschland",
  rheydter_kinos_cinema_movie: "rheydter-kinos-cinema-movie",
  atelier_kino: "atelier-kino",
  ctc_filmtheater: "ctc-filmtheater",
  vereinigte_lichtspiele: "vereinigte-lichtspiele",
  rialto_palast: "rialto-palast",
  gabriel_filmtheater: "gabriel-filmtheater",
  kinocenter_maxhuette_preissner_winkler:
    "kinocenter-maxhuette-preissner-winkler",
  bavaria_filmtheater: "bavaria-filmtheater",
  inselkino_open_air_auf_der_freundschaftsinsel:
    "inselkino-open-air-auf-der-freundschaftsinsel",
  odeon_filmtheater: "odeon-filmtheater",
  passage_kinos: "passage-kinos",
  filmtheater_valentin: "filmtheater-valentin",
  herzog_filmtheater: "herzog-filmtheater",
  kurbelkiste: "kurbelkiste",
  theater_werkstatt: "theater-werkstatt",
  neues_ut: "neues-ut",
  sirch_kino: "sirch-kino",
  japanisches_kulturinstitut: "japanisches-kulturinstitut",
  kino_lido: "kino-lido",
  autokino_zempow: "autokino-zempow",
  kino_sued: "kino-sued",
  luxor_filmtheater: "luxor-filmtheater",
  blaue_koenigin: "blaue-koenigin",
  kino_malchin: "kino-malchin",
  orpheum_lichtspiele: "orpheum-lichtspiele",
  campingplatz_arendsee: "campingplatz-arendsee",
  lichtwerk_kultur: "lichtwerk-kultur",
  melodrom_filmtheater: "melodrom-filmtheater",
  moritzbastei: "moritzbastei",
  treffpunkt_rotebuehlplatz: "treffpunkt-rotebuehlplatz",
  kommunales_kino_coesfeld: "kommunales-kino-coesfeld",
  motorenhalle: "motorenhalle",
  bunker_d: "bunker-d",
  gloria_theater_neuenrade: "gloria-theater-neuenrade",
  savoy_theater: "savoy-theater",
  eldorado_kino: "eldorado-kino",
  filmclub_813: "filmclub-813",
  city_lichtspiele: "city-lichtspiele",
  dortmunder_u: "dortmunder-u",
  kino_im_kursaal: "kino-im-kursaal",
  clubkino_passage: "clubkino-passage",
  kino_malchow: "kino-malchow",
  alb_lichtspiele: "alb-lichtspiele",
  kino_im_badehaus_masserberg: "kino-im-badehaus-masserberg",
  ssf_autokino: "ssf-autokino",
  club_vaudeville: "club-vaudeville",
  open_air_auf_dem_konzertplatz_weisser_hirsch:
    "open-air-auf-dem-konzertplatz-weisser-hirsch",
  filmtheater_beach_club: "filmtheater-beach-club",
  cinematheque_kino_im_grassi_museum: "cinematheque-kino-im-grassi-museum",
  reinfelder_lichtspiele_kino: "reinfelder-lichtspiele-kino",
  sommerkino_wustrow: "sommerkino-wustrow",
  roter_saal: "roter-saal",
  black_box: "black-box",
  walhalla_studio: "walhalla-studio",
  filmwerk_orange: "filmwerk-orange",
  deutsches_filmmuseum: "deutsches-filmmuseum",
  binchen_kommunales_kino: "binchen-kommunales-kino",
  wasgau_theater: "wasgau-theater",
  kino_cafe: "kino-cafe",
  kommunales_kino_im_jokus: "kommunales-kino-im-jokus",
  kinett: "kinett",
  central_lichtspiele: "central-lichtspiele",
  wittinger_lichtspiele: "wittinger-lichtspiele",
  ostsee_welten_5d: "ostsee-welten-5d",
  rastatter_kinowinter_in_der_reithalle:
    "rastatter-kinowinter-in-der-reithalle",
  saturn_kino: "saturn-kino",
  felleshus: "felleshus",
  filmtheater_universum: "filmtheater-universum",
  pinakothek_der_moderne: "pinakothek-der-moderne",
  kursaal_haus_des_gastes: "kursaal-haus-des-gastes",
  kino_im_klinikum: "kino-im-klinikum",
  mobiles_kino_an_der_johannisbruecke: "mobiles-kino-an-der-johannisbruecke",
  kulturfabrik_alsteinklub: "kulturfabrik-alsteinklub",
  cafe_zentral: "cafe-zentral",
  maerkisches_kino: "maerkisches-kino",
  filme_im_schloss: "filme-im-schloss",
  lichthaus_kino_im_strassenbahndepot_e_werk:
    "lichthaus-kino-im-strassenbahndepot-e-werk",
  kino_im_filmbuero: "kino-im-filmbuero",
  blitz_lichtspiele: "blitz-lichtspiele",
  erlebniskino_berli: "erlebniskino-berli",
  heimgarten_kino: "heimgarten-kino",
  club_d: "club-d",
  literaturhaus_berlin: "literaturhaus-berlin",
  ernemann_vii_b_museumskino: "ernemann-vii-b-museumskino",
  kommunales_kino_klappe_11: "kommunales-kino-klappe-11",
  filmclub_wuerzburg: "filmclub-wuerzburg",
  stuki_76: "stuki-76",
  filmwerkstatt: "filmwerkstatt",
  film_casino: "film-casino",
  free_cinema: "free-cinema",
  kommunales_guckloch_kino: "kommunales-guckloch-kino",
  unikino_hannover: "unikino-hannover",
  kommunales_kino_stiftshof: "kommunales-kino-stiftshof",
  kino_casablanca: "kino-casablanca",
  filmclub_comma: "filmclub-comma",
  kim_kino_im_einstein: "kim-kino-im-einstein",
  s_kino_im_jakobmayer: "s-kino-im-jakobmayer",
  kreuz_kino_im_kuz_museumscafe: "kreuz-kino-im-kuz-museumscafe",
  cinema_in_kuesters_hof: "cinema-in-kuesters-hof",
  institut_francais: "institut-francais",
  kinosaal_im_stadtzentrum: "kinosaal-im-stadtzentrum",
  open_end_kino_im_vhs_gebaeude: "open-end-kino-im-vhs-gebaeude",
  kommunales_kino_im_saal_des_hotel_restaurants_linde:
    "kommunales-kino-im-saal-des-hotel-restaurants-linde",
  ajz_chemnitz: "ajz-chemnitz",
  lucky_s_luke: "lucky-s-luke",
  kino_im_cafe_trauma: "kino-im-cafe-trauma",
  rathaus_rotenburg: "rathaus-rotenburg",
  kino_cafe_am_ufer: "kino-cafe-am-ufer",
  clubheim_schanzenpark: "clubheim-schanzenpark",
  kljb_kinderkino_essenheim: "kljb-kinderkino-essenheim",
  kljb_kinderkino_hessloch: "kljb-kinderkino-hessloch",
  kljb_kinderkino_offstein: "kljb-kinderkino-offstein",
  kljb_kinderkino_loerzweiler: "kljb-kinderkino-loerzweiler",
  kljb_kinderkino_gau_bickelheim: "kljb-kinderkino-gau-bickelheim",
  kljb_kinderkino_abenheim: "kljb-kinderkino-abenheim",
  puki: "puki",
  palastkino: "palastkino",
  ha_rai_kino: "ha-rai-kino",
  carl_orff_saal: "carl-orff-saal",
  kinder_und_jugendeinrichtung_glashuette_porz:
    "kinder-und-jugendeinrichtung-glashuette-porz",
  kleines_kino_audimax_der_europa_universitaet:
    "kleines-kino-audimax-der-europa-universitaet",
  stadtbibliothek_radebeul_ost: "stadtbibliothek-radebeul-ost",
  kommunales_kino_im_kik: "kommunales-kino-im-kik",
  burgbuehne_s_freche_hus: "burgbuehne-s-freche-hus",
  akademie_der_kuenste: "akademie-der-kuenste",
  bar_jeder_sicht: "bar-jeder-sicht",
  hansafilmpalast: "hansafilmpalast",
  kinostar: "kinostar",
  afk_filmstudio_an_der_uni: "afk-filmstudio-an-der-uni",
  altes_kino_frotheim: "altes-kino-frotheim",
  aries_images: "aries-images",
  astoria_kino: "astoria-kino",
  atelier_scheunenkino: "atelier-scheunenkino",
  athanor_akademie_freundlhalle: "athanor-akademie-freundlhalle",
  audio_visions: "audio-visions",
  autokino_saarland: "autokino-saarland",
  autokino_schlema: "autokino-schlema",
  babylon_kino_club_mehr: "babylon-kino-club-mehr",
  bel_etage: "bel-etage",
  berliner_filmtheater_knapp: "berliner-filmtheater-knapp",
  cinema_filmkunsttheater: "cinema-filmkunsttheater",
  das_filmcafe: "das-filmcafe",
  eifel_lichtspiele: "eifel-lichtspiele",
  filmclub_blendwerk: "filmclub-blendwerk",
  filmclub_kassablanka: "filmclub-kassablanka",
  filmeck: "filmeck",
  filmklub: "filmklub",
  freilichttheater_am_stoa: "freilichttheater-am-stoa",
  freiluftkino: "freiluftkino",
  fribbemaxx_open_air_kino: "fribbemaxx-open-air-kino",
  kinderfilmhaus: "kinderfilmhaus",
  komoedie_ruegen: "komoedie-ruegen",
  kurbel_filmtheater: "kurbel-filmtheater",
  kurfuerst_lichtspiele: "kurfuerst-lichtspiele",
  maxx5d_kino_show: "maxx5d-kino-show",
  meininger_filmtheater: "meininger-filmtheater",
  metropol_duesseldorfer_filmkunstkino: "metropol-duesseldorfer-filmkunstkino",
  open_air_jugendherberge_landungsbruecken:
    "open-air-jugendherberge-landungsbruecken",
  open_air_kino_im_freibad: "open-air-kino-im-freibad",
  panoptikum: "panoptikum",
  parkbuehne: "parkbuehne",
  passage_kino_center: "passage-kino-center",
  patch_barracks_theater: "patch-barracks-theater",
  provinz_80_programmkino: "provinz-80-programmkino",
  p_team_filmtheater: "p-team-filmtheater",
  schulkino: "schulkino",
  sportspig_sportskino: "sportspig-sportskino",
  spreewald_lichtspiele: "spreewald-lichtspiele",
  staatstheater_cottbus_kammerbuehne: "staatstheater-cottbus-kammerbuehne",
  stern_lichtspielhaus: "stern-lichtspielhaus",
  strandkino: "strandkino",
  unikino: "unikino",
  hochseekino: "hochseekino",
  lederpalast_kino: "lederpalast-kino",
  kino_gandeon: "kino-gandeon",
  konzerthaus_dortmund: "konzerthaus-dortmund",
  mansergh_hall: "mansergh-hall",
  the_kaleidoscope: "the-kaleidoscope",
  open_air_kino_im_schlachtgarten: "open-air-kino-im-schlachtgarten",
  open_air_kulturufer: "open-air-kulturufer",
  cp_lichtspiele: "cp-lichtspiele",
  autokino_berlin_am_grossflughafen_ber:
    "autokino-berlin-am-grossflughafen-ber",
  open_air_residenz_hilpoltstein: "open-air-residenz-hilpoltstein",
  open_air_herzogenaurach: "open-air-herzogenaurach",
  open_air_kino_beim_grosswirt_in_mirskofen:
    "open-air-kino-beim-grosswirt-in-mirskofen",
  open_air_museumspark_schwabach: "open-air-museumspark-schwabach",
  open_air_kino_am_kirchplatz: "open-air-kino-am-kirchplatz",
  open_air_kino_am_see: "open-air-kino-am-see",
  open_air_kino_ballmertshofer_filmfest:
    "open-air-kino-ballmertshofer-filmfest",
  open_air_kino_kino_an_der_orangerie: "open-air-kino-kino-an-der-orangerie",
  open_air_kino_an_der_totenkirche: "open-air-kino-an-der-totenkirche",
  open_air_kino_im_kaffeemuseum: "open-air-kino-im-kaffeemuseum",
  open_air_schlosspark: "open-air-schlosspark",
  sommerkino_open_air_zeitraumexit_hof: "sommerkino-open-air-zeitraumexit-hof",
  open_air_am_landhaus_dessau: "open-air-am-landhaus-dessau",
  open_air_naturgartenbad: "open-air-naturgartenbad",
  kleines_kino_4_generationen_park: "kleines-kino-4-generationen-park",
  open_air_auf_aeg: "open-air-auf-aeg",
  sommerkino_im_garten_des_schillerhauses:
    "sommerkino-im-garten-des-schillerhauses",
  freiluftkino_am_spreebogen: "freiluftkino-am-spreebogen",
  freizeitanlage_taubenheim: "freizeitanlage-taubenheim",
  babylon_open_air_freilichtbuehne_stadtpark_fuerth:
    "babylon-open-air-freilichtbuehne-stadtpark-fuerth",
  die_freilichtbuehne_open_air_kino: "die-freilichtbuehne-open-air-kino",
  sommerhofkino_schwabehaus: "sommerhofkino-schwabehaus",
  sommerkino_am_museumshof: "sommerkino-am-museumshof",
  open_air_am_b_o_parkhotel: "open-air-am-b-o-parkhotel",
  freilichtkino_doelitzer_wassermuehle: "freilichtkino-doelitzer-wassermuehle",
  autokino_und_open_air_kino_voelklingen:
    "autokino-und-open-air-kino-voelklingen",
  open_air_kino: "open-air-kino",
  parkbuehne_fuerstenwalde: "parkbuehne-fuerstenwalde",
  filmnaechte_auf_dem_theaterplatz: "filmnaechte-auf-dem-theaterplatz",
  open_air_schifferstadt: "open-air-schifferstadt",
  open_air_kino_im_braunshardter_taennchen:
    "open-air-kino-im-braunshardter-taennchen",
  open_air_kino_in_den_reisinger_anlagen:
    "open-air-kino-in-den-reisinger-anlagen",
  kuki_on_tour_schloss_fasanerie: "kuki-on-tour-schloss-fasanerie",
  sommernachtskino_im_van_ameren_bad: "sommernachtskino-im-van-ameren-bad",
  mittendrin_kinonaechte_auf_dem_ochsenfurter_marktplatz:
    "mittendrin-kinonaechte-auf-dem-ochsenfurter-marktplatz",
  open_air_kino_am_filzteich: "open-air-kino-am-filzteich",
  open_air_im_freibad_friedrichsdorf: "open-air-im-freibad-friedrichsdorf",
  sommer_kino_naechte_auf_dem_aussengelaende_der_reithalle:
    "sommer-kino-naechte-auf-dem-aussengelaende-der-reithalle",
  open_air_kino_im_friesdorfer_freibad_friesi:
    "open-air-kino-im-friesdorfer-freibad-friesi",
  kiezkinotour_babylon_open_air_indoor: "kiezkinotour-babylon-open-air-indoor",
  open_air_kino_aachen: "open-air-kino-aachen",
  open_air_im_stadtbad: "open-air-im-stadtbad",
  open_air_im_schlossgarten_wewelsburg: "open-air-im-schlossgarten-wewelsburg",
  open_air_an_der_dreckburg: "open-air-an-der-dreckburg",
  open_air_kino_jungendtreff_neustueckweg:
    "open-air-kino-jungendtreff-neustueckweg",
  open_air_makk_museum_fuer_angewandte_kunst:
    "open-air-makk-museum-fuer-angewandte-kunst",
  gut_hellersdorf_open_air_kino: "gut-hellersdorf-open-air-kino",
  open_air_brueckenkopf_park: "open-air-brueckenkopf-park",
  open_air_kino_vor_der_schlossberghalle:
    "open-air-kino-vor-der-schlossberghalle",
  sommer_kino_auf_der_burg_lindenfels: "sommer-kino-auf-der-burg-lindenfels",
  open_air_kino_im_fraenkischen_freilandmuseum:
    "open-air-kino-im-fraenkischen-freilandmuseum",
  arkadenhof_der_bonner_universitaet_am_hof:
    "arkadenhof-der-bonner-universitaet-am-hof",
  open_air_kino_bad_wuennenberg: "open-air-kino-bad-wuennenberg",
  open_air_kino_istha: "open-air-kino-istha",
  theater_im_kurhaus: "theater-im-kurhaus",
  delphi_lux: "delphi-lux",
  aischtaler_filmtheater: "aischtaler-filmtheater",
  lodderbast: "lodderbast",
  open_air_kino_hofladen_zur_muehle: "open-air-kino-hofladen-zur-muehle",
  bernd_bosse: "bernd-bosse",
  open_air_kino_am_marktplatz: "open-air-kino-am-marktplatz",
  open_air_burgruine_hanstein: "open-air-burgruine-hanstein",
  open_air_kino_tetzelschloss: "open-air-kino-tetzelschloss",
  kino_am_campingpark_rerik: "kino-am-campingpark-rerik",
  cinebaar: "cinebaar",
  mousonturm: "mousonturm",
  filmtheater_stadt_hamburg: "filmtheater-stadt-hamburg",
  seniorenkino_st_georgen_st_georgen_im_schwarzwald:
    "seniorenkino-st-georgen-st-georgen-im-schwarzwald",
  kulturkirche_st_stephani: "kulturkirche-st-stephani",
  parkside_studios_offenbach_offenbach_am_main:
    "parkside-studios-offenbach-offenbach-am-main",
  filmrausch_das_hdm_kino: "filmrausch-das-hdm-kino",
  evented_gmbh: "evented-gmbh",
  nomadenkino_open_air_im_about_blank: "nomadenkino-open-air-im-about-blank",
  freiluftkino_am_tonwerk_dorfen_dorfen:
    "freiluftkino-am-tonwerk-dorfen-dorfen",
  open_air_kino_in_groemitz_hamburg: "open-air-kino-in-groemitz-hamburg",
  freilichtkino_scholle_34: "freilichtkino-scholle-34",
  open_air_kino_stammheim_stuttgart: "open-air-kino-stammheim-stuttgart",
  olympia_open_air_kino: "olympia-open-air-kino",
  kuki_on_tour: "kuki-on-tour",
  open_air_herrenschiesshaus: "open-air-herrenschiesshaus",
  open_air_kino_auf_dem_gellertberg: "open-air-kino-auf-dem-gellertberg",
  open_air_kino_im_toskanapark: "open-air-kino-im-toskanapark",
  open_air_kino_auf_dem_dreiecksplatz: "open-air-kino-auf-dem-dreiecksplatz",
  lamm_lichtspiele_open_air: "lamm-lichtspiele-open-air",
  sommerkino_auf_dem_alsterdorfer_markt:
    "sommerkino-auf-dem-alsterdorfer-markt",
  vaihinger_open_air_kino_vaihingen_an_der_enz:
    "vaihinger-open-air-kino-vaihingen-an-der-enz",
  open_air_kirchplatz_st_ludwig: "open-air-kirchplatz-st-ludwig",
  open_air_kino_in_der_wilhelmsburg: "open-air-kino-in-der-wilhelmsburg",
  kino_kaarst_forum_der_staedt_realschule:
    "kino-kaarst-forum-der-staedt-realschule",
  inselkino_baltrum_5d88b3e45970c: "inselkino-baltrum-5d88b3e45970c",
  festspielhaus_hellerau: "festspielhaus-hellerau",
  kino_im_kunstmuseum: "kino-im-kunstmuseum",
  russisches_haus_der_wissenschaft_und_kultur:
    "russisches-haus-der-wissenschaft-und-kultur",
  filmclub_akasava: "filmclub-akasava",
  alte_muenze_haus_3: "alte-muenze-haus-3",
  autokino_naumburg: "autokino-naumburg",
  autokino_oelde_oelde: "autokino-oelde-oelde",
  autokino_lippetal_herzfeld_lippetal: "autokino-lippetal-herzfeld-lippetal",
  rieder_s_autokino_essenbach: "rieder-s-autokino-essenbach",
  autokino_erkelenz_erkelenz: "autokino-erkelenz-erkelenz",
  autokino_karlsruhe_karlsruhe: "autokino-karlsruhe-karlsruhe",
  autokino_hagen_5eb430890b27b: "autokino-hagen-5eb430890b27b",
  autokino_wismar_wismar: "autokino-wismar-wismar",
  autokino_chemnitz_chemnitz: "autokino-chemnitz-chemnitz",
  benefiz_autokino_bad_lippspringe_bad_lippspringe:
    "benefiz-autokino-bad-lippspringe-bad-lippspringe",
  autokino_waldshut_waldshut_tiengen: "autokino-waldshut-waldshut-tiengen",
  autokino_st_ingbert_st_ingbert: "autokino-st-ingbert-st-ingbert",
  autokino_karpfhamer_festwiese_bad_griesbach_i_rottal:
    "autokino-karpfhamer-festwiese-bad-griesbach-i-rottal",
  autokino_sommer_2020_kaiserslautern: "autokino-sommer-2020-kaiserslautern",
  autokino_friedrichshafen: "autokino-friedrichshafen",
  filmarena_jena: "filmarena-jena",
  festplatz_am_walkmuehlenweg_herborn: "festplatz-am-walkmuehlenweg-herborn",
  autokino_festival_oldenburg_oldenburg:
    "autokino-festival-oldenburg-oldenburg",
  autokino_augsburg_messeflimmern: "autokino-augsburg-messeflimmern",
  open_air_alter_bauhof: "open-air-alter-bauhof",
  stollberger_filmnaechte_stollberg_erzgeb:
    "stollberger-filmnaechte-stollberg-erzgeb",
  kulturwerkstatt_auf_aeg: "kulturwerkstatt-auf-aeg",
  eventlocation_eck_mengkofen: "eventlocation-eck-mengkofen",
  warnemuende_rostock: "warnemuende-rostock",
  univary_autokino_eventkino_schleiz_oettersdorf:
    "univary-autokino-eventkino-schleiz-oettersdorf",
  univary_autokino_torgau_torgau: "univary-autokino-torgau-torgau",
  autokino_lichtspielgarten_stade_5fbfa6db28673:
    "autokino-lichtspielgarten-stade-5fbfa6db28673",
  autokino_ferropolis_graefenhainichen: "autokino-ferropolis-graefenhainichen",
  autokino_ruethen_ruethen: "autokino-ruethen-ruethen",
  autokino_bamberg_hallstadt: "autokino-bamberg-hallstadt",
  autokino_hoechstadt_an_der_aisch_hoechstadt:
    "autokino-hoechstadt-an-der-aisch-hoechstadt",
  roadmovies_leipzig_leipzig: "roadmovies-leipzig-leipzig",
  duesseldorfer_heimatsommer_open_air_kino_duesseldorf:
    "duesseldorfer-heimatsommer-open-air-kino-duesseldorf",
  autokino_melle: "autokino-melle",
  autokino_sylt_sylt: "autokino-sylt-sylt",
  galopprennbahn_hamburg_horn_hamburg: "galopprennbahn-hamburg-horn-hamburg",
  buedinger_autokino_2021_buedingen: "buedinger-autokino-2021-buedingen",
  sommerkino_schloss_charlottenburg: "sommerkino-schloss-charlottenburg",
  kino_im_schlossgarten_altensteig_60ba4e04d27a2:
    "kino-im-schlossgarten-altensteig-60ba4e04d27a2",
  picknick_kino_karlsruhe_60df380da8891:
    "picknick-kino-karlsruhe-60df380da8891",
  starmexx_filmnaechte_in_burglengenfeld:
    "starmexx-filmnaechte-in-burglengenfeld",
  insel_berlin: "insel-berlin",
  anfahrt: "anfahrt",
  wissensstadt_sommerkino_berlin_60dfe0ceebfe8:
    "wissensstadt-sommerkino-berlin-60dfe0ceebfe8",
  open_air_gueglingen: "open-air-gueglingen",
  sommerkino_im_altwerk_ruesselsheim: "sommerkino-im-altwerk-ruesselsheim",
  autokino_pinneberg_pinneberg: "autokino-pinneberg-pinneberg",
  revier_suedost_new_griessmuehle_location:
    "revier-suedost-new-griessmuehle-location",
  wellenwerk_deus_temple_berlin: "wellenwerk-deus-temple-berlin",
  stadthalle_schoenau: "stadthalle-schoenau",
  magic_cinema_4d_im_europa_park: "magic-cinema-4d-im-europa-park",
  refugio_theatre_neukoelln: "refugio-theatre-neukoelln",
  autokino_heinsberg_12345: "autokino-heinsberg-12345",
  open_air_kino_62e8dde6b42df: "open-air-kino-62e8dde6b42df",
  kino_in_der_stadtbibliothek: "kino-in-der-stadtbibliothek",
  kulturhaus_der_stadt_weissenfels: "kulturhaus-der-stadt-weissenfels",
  sommerkino_auf_dem_cranach_hof: "sommerkino-auf-dem-cranach-hof",
  open_air_kino_am_skulpturenmuseum: "open-air-kino-am-skulpturenmuseum",
  open_air_kino_im_freihof_gedenkstaette:
    "open-air-kino-im-freihof-gedenkstaette",
  pfingstberg: "pfingstberg",
  open_air_kuhrhaus_terrassen_im_hotel_dolce:
    "open-air-kuhrhaus-terrassen-im-hotel-dolce",
  open_air_im_alten_hofgut: "open-air-im-alten-hofgut",
  open_air_schwimmbad_heusenstamm: "open-air-schwimmbad-heusenstamm",
  open_air_vor_dem_rheingauer_dom: "open-air-vor-dem-rheingauer-dom",
  open_air_kino_im_grubenfeld: "open-air-kino-im-grubenfeld",
  open_air_kino_schlossruine: "open-air-kino-schlossruine",
  open_air_an_der_felsenbuehne_im_schlosspark_buckow:
    "open-air-an-der-felsenbuehne-im-schlosspark-buckow",
  open_air_kino_insel_lichtspiele_e_v: "open-air-kino-insel-lichtspiele-e-v",
  lukas_kulinarischer_bahnhof: "lukas-kulinarischer-bahnhof",
  open_air_kino_hofgeismar: "open-air-kino-hofgeismar",
  zeltival_kino_im_valentinspark: "zeltival-kino-im-valentinspark",
  open_air_kino_am_vegesacker_balkon: "open-air-kino-am-vegesacker-balkon",
  open_air_kino_innenhof_der_neuburg: "open-air-kino-innenhof-der-neuburg",
  gaismarkter_kino_open_air: "gaismarkter-kino-open-air",
  open_air_kino_zwischen_den_schanzen_erdinger_arena:
    "open-air-kino-zwischen-den-schanzen-erdinger-arena",
  open_air_kino_ottersweier: "open-air-kino-ottersweier",
  open_air_nagold: "open-air-nagold",
  open_air_schloss_neuenbuerg_schlosshof:
    "open-air-schloss-neuenbuerg-schlosshof",
  volkstheater_operetten_kino_im_engelsaal_lichtspielhaus:
    "volkstheater-operetten-kino-im-engelsaal-lichtspielhaus",
  schlosstheater_in_der_mensa_des_ekg: "schlosstheater-in-der-mensa-des-ekg",
  alpamare: "alpamare",
  kino_in_wilhelm_13: "kino-in-wilhelm-13",
  kulturfabrik_krefeld: "kulturfabrik-krefeld",
  kiezkinotour_babylon_open_air_indoor_64885a6dd5c8e:
    "kiezkinotour-babylon-open-air-indoor-64885a6dd5c8e",
  kiezkinotour_babylon_open_air_indoor_64885a6de4327:
    "kiezkinotour-babylon-open-air-indoor-64885a6de4327",
  kartaeuserkirche_im_germanischen_nationalmuseum:
    "kartaeuserkirche-im-germanischen-nationalmuseum",
  open_air_im_biergarten_theresienhof: "open-air-im-biergarten-theresienhof",
  open_air_kino_nuertingen: "open-air-kino-nuertingen",
  open_air_appelhof: "open-air-appelhof",
  kiezkinotour_babylon_open_air_indoor_64885a6e49f5e:
    "kiezkinotour-babylon-open-air-indoor-64885a6e49f5e",
  waldbuehne: "waldbuehne",
  open_air_kinofabrik: "open-air-kinofabrik",
  open_air_im_lueneburger_kurpark: "open-air-im-lueneburger-kurpark",
  sommer_kino_naechte: "sommer-kino-naechte",
  insel_kino_ateliergemeinschaft_elbinsel_kunst:
    "insel-kino-ateliergemeinschaft-elbinsel-kunst",
  open_air_kino_filmwelt: "open-air-kino-filmwelt",
  sommerkino: "sommerkino",
  batavia_freilichtkino_theaterschiff_batavia:
    "batavia-freilichtkino-theaterschiff-batavia",
  open_air_kino_bad_driburg: "open-air-kino-bad-driburg",
  open_air_kino_am_berg: "open-air-kino-am-berg",
  theater_am_goetheplatz: "theater-am-goetheplatz",
  bali_filmtheaterbetriebsge_sellschaft_mbh:
    "bali-filmtheaterbetriebsge-sellschaft-mbh",
  galli_theater_e_v: "galli-theater-e-v",
  theater_akki_axel_mueller: "theater-akki-axel-mueller",
  syjo_theater_sylvie_jourdan: "syjo-theater-sylvie-jourdan",
  reit_und_fahrverein_reichenbach_e_v: "reit-und-fahrverein-reichenbach-e-v",
  theater_spektakel_klaus_fischbach: "theater-spektakel-klaus-fischbach",
  stefan_schaich_kino_betriebs_gmbh: "stefan-schaich-kino-betriebs-gmbh",
  ralf_cinetropolis_kinobetriebe: "ralf-cinetropolis-kinobetriebe",
  wiemers: "wiemers",
  ehemaliges_lifa_kino: "ehemaliges-lifa-kino",
  live_im_kino: "live-im-kino",
  kieft_projektentwicklung_gmbh: "kieft-projektentwicklung-gmbh",
  farken_enterprises: "farken-enterprises",
  karlheinz_pauli: "karlheinz-pauli",
  theater_doris_batzler: "theater-doris-batzler",
  kinospot_de_werbefilm_gbr_nathalie_somville:
    "kinospot-de-werbefilm-gbr-nathalie-somville",
  home_cinema_concept: "home-cinema-concept",
  guenther_steigner: "guenther-steigner",
  viktor: "viktor",
  das_kino_arbeitsgemeinschaft_film_e_v_kasse:
    "das-kino-arbeitsgemeinschaft-film-e-v-kasse",
  werner_wuerth: "werner-wuerth",
  open_air_bischofsheim: "open-air-bischofsheim",
  open_air_kino_borghorst: "open-air-kino-borghorst",
  schlossberg_gaststaette: "schlossberg-gaststaette",
  kino_unterm_sternenhimmel: "kino-unterm-sternenhimmel",
  schlosshof_vor_dem_rathaus: "schlosshof-vor-dem-rathaus",
  kino_unterm_ostseehimmel: "kino-unterm-ostseehimmel",
  open_air_64885a71621dd: "open-air-64885a71621dd",
  zeche_fuerst_leopold: "zeche-fuerst-leopold",
  hff_kino: "hff-kino",
  kino_im_stadthaus_64885a71ab19f: "kino-im-stadthaus-64885a71ab19f",
  campbell_barracks: "campbell-barracks",
  franz_ulrich: "franz-ulrich",
  yaam: "yaam",
  klingemuehle: "klingemuehle",
  birgit_bier: "birgit-bier",
  warehouse_cinema: "warehouse-cinema",
  sunset_cinema_neuzeit_ost: "sunset-cinema-neuzeit-ost",
  kino_im_park_gemmingen: "kino-im-park-gemmingen",
  mobile_kino_schlossgut_finowfurt: "mobile-kino-schlossgut-finowfurt",
  mobile_kino_schleusenkrug: "mobile-kino-schleusenkrug",
};
