export const canonicalizeTag = (tag: string): string => {
  const cleaned = tag.trim().replace(/^auf\s+/i, "");
  const normalized = cleaned.toLowerCase().replace(/\s+/g, " ");

  const mapping: Record<string, string> = {
    ov: "OV",
    omu: "OmU",
    omeu: "OmEU",
    "2d": "2D",
    "3d": "3D",
    imax: "IMAX",
    dolby: "Dolby",
    "dolby atmos": "Dolby Atmos",
    preview: "Preview",
    sneak: "Sneak",
    english: "English",
    englisch: "English",
    "engl.": "English",
    "englische fassung": "English",
    "deutsche fassung": "Deutsche Fassung",
    "dt fassung": "Deutsche Fassung",
    "70mm": "70mm",
    "70 mm": "70mm",
    "70-mm": "70mm",
    "70mm fassung": "70mm",
    "70 mm fassung": "70mm",
    "35mm": "35mm",
    "35 mm": "35mm",
    "35-mm": "35mm",
    "35mm fassung": "35mm",
    "35 mm fassung": "35mm",
    "4k": "4K",
    hfr: "HFR",
    screenx: "ScreenX",
    "4dx": "4DX",
    laser: "Laser",
    "open air": "Open Air",
    "open-air": "Open Air",
    openair: "Open Air",
    "open air kino": "Open Air",
    "ein eberhofer krimi": "Eberhofer-Krimi",
    "ein eberhofer-krimi": "Eberhofer-Krimi",
    "eberhofer krimi": "Eberhofer-Krimi",
    "eberhofer-krimi": "Eberhofer-Krimi",
    eberhofer: "Eberhofer-Krimi",
    "everything must go": "Everything Must Go",
    "everything must go edition": "Everything Must Go",
    "everything must go version": "Everything Must Go",
    cinemathek: "CineMathek",
    cineclassic: "CineClassic",
    cinesneak: "CineSneak",
    "senioren kino": "Seniorenkino",
    "kino für senioren": "Seniorenkino",
    seniorenkino: "Seniorenkino",
    "premieren abend": "Premierenabend",
    "vhs-filmclub": "VHS-Filmclub",
    frühstück: "Frühstück",
    leuchtturmveranstaltung: "Leuchtturmveranstaltung",
    strickkino: "Strickkino",
    shorts: "SHORTS",
    doku: "Doku",
    ln: "Ladies Night",
    "cinepride - dein pinkmonday": "CinePride - PinkMonday",
    cinepride: "CinePride",
    pinkmonday: "PinkMonday",
    "kino café": "Kino Café",
    "kino cafe": "Kino Café",
    montagsfilm: "Montagsfilm",
    boc: "Best of Cinema",
    "best of cinema": "Best of Cinema",
    koki: "Kommunales Kino",
    cinespecial: "CineSpecial",
    "k+k": "K+K",
    cinemoments: "CineMoments",
    "malteser film café": "Malteser Film Café",
    "malteser film cafe": "Malteser Film Café",
    ukrainisch: "Ukrainisch",
    "ukrainische fassung": "Ukrainisch",
    ukr: "Ukrainisch",
    "ukr.": "Ukrainisch",
    arab: "Arabisch",
    "arab.": "Arabisch",
    vietnam: "Vietnamesisch",
    "vietnam.": "Vietnamesisch",
    span: "Spanisch",
    "span.": "Spanisch",
    türk: "Türkisch",
    "türk.": "Türkisch",
    mehrspr: "Mehrsprachig",
    "mehrspr.": "Mehrsprachig",
    "live action": "Live Action",
    "extended version": "Extended Version",
    "extended edition": "Extended Edition",
    extended: "Extended Version",
    "ext. version": "Extended Version",
    "ext version": "Extended Version",
    ext: "Extended Version",
    "director's cut": "Director's Cut",
    "directors cut": "Director's Cut",
    uncut: "Uncut",
    wiederaufführung: "Wiederaufführung",
    wa: "Wiederaufführung",
    "4k remastered": "4K Remastered",
    remastered: "Remastered",
    restored: "Restored",
    df: "DF",
    of: "OF",
    met: "MET Opera",
    "met opera": "MET Opera",
    rbo: "RBO Live",
    "rbo live": "RBO Live",
  };

  if (normalized.startsWith("cinestricken")) {
    return cleaned.replace(/cinestricken/i, "CineStricken");
  }

  if (normalized.startsWith("met")) {
    return "MET Opera";
  }

  if (normalized.startsWith("rbo")) {
    return "RBO Live";
  }

  return mapping[normalized] ?? cleaned;
};
