// Erweiterte Metadaten-Marker (Wichtig: alles in Kleinschreibung und ohne Akzente)
export const METADATA_MARKERS = [
  "ov",
  "omu",
  "omeu",
  "2d",
  "3d",
  "imax",
  "dolby",
  "atmos",
  "preview",
  "sneak",
  "fsk",
  "dt fassung",
  "deutsche fassung",
  "englische fassung",
  "ukrainische fassung",
  "turkische fassung",
  "spanische fassung",
  "italienische fassung",
  "franzosische fassung",
  "sprachfassung",
  "df",
  "of",
  "omud",
  "ovd",
  "original version",
  "originalfassung",
  "untertitel",
  "english",
  "englisch",
  "70mm",
  "70 mm",
  "35mm",
  "35 mm",
  "4k",
  "hfr",
  "screenx",
  "4dx",
  "laser",
  "ukrainisch",
  "ukr",
  "arab",
  "vietnam",
  "span",
  "mehrspr",
  "turk",
  "engl",
  "montagsfilm",
  "malteser film cafe",
  "live action",
  "extended version",
  "extended edition",
  "extended",
  "ext version",
  "ext fassung",
  "ext",
  "directors cut",
  "uncut",
  "wiederauffuhrung",
  "wa",
  "jubilaumsausgabe",
  "jubilaum",
  "re-release",
  "rerelease",
  "live ubertragung",
  "liveubertragung",
  "live",
  "4k remastered",
  "remastered",
  "restored",
  "edition",
];

// Pre-compiled regex for testing metadata markers to prevent massive instantiation overhead in loops
export const METADATA_REGEX = new RegExp(
  `\\b(${METADATA_MARKERS.join("|")})\\b`,
  "i",
);
