export const canonicalizeTag = (tag: string): string => {
    const cleaned = tag.trim().replace(/^auf\s+/i, "");
    const normalized = cleaned.toLowerCase().replace(/\s+/g, " ");

    const mapping: Record<string, string> = {
        ov: "OV",
        omu: "OmU",
        omeu: "OmEU",
        "2d": "2D",
        "3d": "3D",
        imax: "IMAX",
        dolby: "Dolby",
        "dolby atmos": "Dolby Atmos",
        preview: "Preview",
        sneak: "Sneak",
        english: "English",
        englisch: "English",
        "engl.": "English",
        "70mm": "70mm",
        "35mm": "35mm",
        "4k": "4K",
        hfr: "HFR",
        screenx: "ScreenX",
        "4dx": "4DX",
        laser: "Laser",
        cinemathek: "CineMathek",
        cineclassic: "CineClassic",
        cinesneak: "CineSneak",
        "senioren kino": "Seniorenkino",
        "kino für senioren": "Seniorenkino",
        seniorenkino: "Seniorenkino",
        "premieren abend": "Premierenabend",
        "vhs-filmclub": "VHS-Filmclub",
        frühstück: "Frühstück",
        leuchtturmveranstaltung: "Leuchtturmveranstaltung",
        strickkino: "Strickkino",
        shorts: "SHORTS",
        doku: "Doku",
        ln: "Ladies Night",
        "cinepride - dein pinkmonday": "CinePride - PinkMonday",
        cinepride: "CinePride",
        pinkmonday: "PinkMonday",
        "kino café": "Kino Café",
        "kino cafe": "Kino Café",
        montagsfilm: "Montagsfilm",
        boc: "Best of Cinema",
        "best of cinema": "Best of Cinema",
        koki: "Kommunales Kino",
        cinespecial: "CineSpecial",
        "k+k": "K+K",
        cinemoments: "CineMoments",
        "malteser film café": "Malteser Film Café",
        "malteser film cafe": "Malteser Film Café",
        ukrainisch: "Ukrainisch",
        "ukrainische fassung": "Ukrainisch",
        ukr: "Ukrainisch",
        "ukr.": "Ukrainisch",
        arab: "Arabisch",
        "arab.": "Arabisch",
        vietnam: "Vietnamesisch",
        "vietnam.": "Vietnamesisch",
        span: "Spanisch",
        "span.": "Spanisch",
        türk: "Türkisch",
        "türk.": "Türkisch",
        mehrspr: "Mehrsprachig",
        "mehrspr.": "Mehrsprachig",
    };

    if (normalized.startsWith("cinestricken")) {
        return cleaned.replace(/cinestricken/i, "CineStricken");
    }

    return mapping[normalized] ?? cleaned;
};
